const chistesMalos = [
    "¿Qué hace una abeja en el gimnasio? ¡Zumba!",
    "¿Por qué los pájaros no usan Facebook? Porque ya tienen Twitter.",
    "¿Qué le dice un semáforo a otro? ¡No me mires, estoy cambiando!",
    "¿Cómo se despiden los químicos? ¡Ácido un placer!",
    "¿Qué hace una vaca en un terremoto? ¡Leche agitada!",
    "¿Por qué los esqueletos no pelean entre ellos? Porque no tienen agallas.",
    "¿Qué le dijo un jardinero a otro? ¡Disfrutemos mientras podamos!",
    "¿Cuál es el café más peligroso del mundo? ¡El ex-preso!",
    "¿Por qué los elefantes no usan computadora? Porque les da miedo el ratón.",
    "¿Qué le dice un pez a otro? ¡Nada!",
    "¿Cuál es el animal más antiguo? La cebra, porque está en blanco y negro.",
    "¿Qué hace un perro con un taladro? ¡Taladrando!",
    "¿Qué le dice una iguana a su hermana gemela? ¡Iguaníta!",
    "¿Qué le dice una pared a otra? ¡Nos vemos en la esquina!",
    "¿Cómo se llama el primo de Bruce Li? Broco Li.",
    "¿Qué hace una computadora en la playa? ¡Navegar!",
    "¿Por qué las focas miran siempre hacia arriba? ¡Porque ahí están los focos!",
    "¿Cuál es el colmo de un electricista? No encontrar su corriente de trabajo.",
    "¿Qué le dice un tomate a otro? ¡Tómate tu tiempo!",
    "¿Qué le dice una cebolla a otra? ¡No llores, estoy aquí!",
    "¿Qué hace un pez en un cine? ¡Nada!",
    "¿Cuál es el animal más feliz? El pingüino, porque siempre lleva un smoking.",
    "¿Qué le dice un perro a su dueño? ¡Guau!",
    "¿Qué pasa si tiras un pato al agua? ¡Nada!",
    "¿Qué hace una vaca con los ojos cerrados? Leche concentrada.",
    "¿Qué hace una abeja en el ordenador? ¡Un buzz de datos!",
    "¿Qué hace un pez con una calculadora? ¡Nada, no sabe usarla!",
    "¿Qué hace una planta cuando tiene sed? ¡Fotosíntesis!",
    "¿Qué le dice un jardinero a otro? ¡Disfrutemos del césped, que a veces se nos va la hierba!",
    "¿Qué hace una roca cuando se aburre? ¡Se petrifica!",
    "¿Cómo se saludan los océanos? ¡Olas!",
    "¿Qué hace un dinosaurio estudiando? ¡Pre-historia!",
    "¿Qué le dice una impresora a otra? ¡Esa hoja es tuya o es impresión mía!",
    "¿Qué hace una serpiente en clase de matemáticas? ¡Sssssuma!",
    "¿Qué hace un pato con un cuchillo? ¡Corta el agua!",
    "¿Qué hace un tomate en el sol? ¡Se pone rojo!",
    "¿Cómo se despiden los italianos? ¡Pasta la vista!",
    "¿Qué hace un pollo en el cine? ¡Pide palomitas!",
    "¿Qué hace un lápiz cuando se aburre? ¡Se saca punta!",
    "¿Por qué los elefantes no usan sombrero? Porque tienen orejas grandes.",
    "¿Qué hace un caracol en el gimnasio? ¡Ejercicio lento!",
    "¿Qué hace un patito en una panadería? ¡Cuac-cakes!",
    "¿Qué hace un plátano en una fiesta? ¡Se pela de risa!",
    "¿Qué hace un dinosaurio en clase? ¡Historia antigua!",
    "¿Qué hace una nube cuando está cansada? ¡Se condensa!",
    "¿Qué hace un pez con gafas? ¡Nada más claro!",
    "¿Qué hace un pez en el río? ¡Nada, nada!",
    "¿Qué hace un ratón en una fiesta? ¡Mueve el queso!",
    "¿Qué hace un astronauta en el bar? ¡Toma espacio!",
    "¿Qué hace una foca en una piscina? ¡Nada feliz!",
    "¿Qué le dijo un pincel al lienzo? Tranquilo, yo te arreglo la vida en colores.",
    "¿Por qué los pintores nunca se deprimen? Porque siempre encuentran cómo darle una nueva capa a todo.",
    "¿Qué hace un cuadro en una sala vacía? Busca su marco de referencia.",
    "¿Qué le dijo un autorretrato a otro? Prefiero estar colgado en el museo que en esta conversación.",
    "¿Por qué el arte moderno nunca pasa hambre? Porque siempre tiene algo abstracto en el plato.",
    "¿Qué le dijo Diego Rivera a un pincel? Si sigues por ese camino, terminarás hecho mural.",
    "¿Sabes cuál es mi tipo de relación favorita? Una tóxica... pero con mucho color.",
    "¿Qué hace un pintor cuando se siente roto? Se pega con óleo.",
    "¿Por qué los cuadros no cuentan secretos? Porque tienen la lengua seca de tanto óleo.",
    "¿Por qué los artistas se enamoran tan fácil? Porque siempre ven el lado más hermoso de las sombras.",
    "¿Qué hace un pincel cuando está celoso? Se mezcla con los colores equivocados.",
    "¿Qué hace un pintor cuando no puede decidirse? Se queda en blanco.",
    "¿Por qué Frida se pintó tantas veces a sí misma? Porque siempre era su mejor modelo... y nunca cobraba.",
    "¿Qué le dijo la paleta de colores al lienzo? Sin mí, serías solo un espacio en blanco.",
    "¿Por qué los artistas nunca están a tiempo? Porque siempre están buscando el momento perfecto para pintar.",
    "¿Qué le dice Frida a la tristeza? Siéntate, que te voy a pintar bonita.",
    "¿Qué hace un pintor cuando está enojado? Derrama todo, pero lo llama arte expresiva.",
    "¿Por qué siempre llevo flores en la cabeza? Para recordarle al mundo que incluso en el dolor hay belleza.",
    "¿Qué le dijo Frida al espejo? Gracias por reflejar todo lo que los demás nunca ven.",
    "¿Por qué no voy al gimnasio? Porque ya cargo con el peso de la vida.",
    "¿Qué hace un reloj deprimido? Pierde el tiempo... igual que yo.",
    "¿Por qué el pan se siente identificado conmigo? Porque siempre termina tostado.",
    "¿Qué le dice un lunes a una persona triste? No te preocupes, yo también soy odiado por todos.",
    "¿Qué hace una nube triste? Llora... igual que yo cuando recuerdo mi vida.",
    "¿Por qué no me gusta el mar? Porque me recuerda que estoy igual de perdido que un pez sin brújula.",
    "¿Qué le dice mi cama cuando me ve? Ven, que aquí sí te quieren.",
    "¿Qué hace una lágrima cuando cae? Piensa: ¡Guau, estoy viviendo la caída libre de mi vida!",
    "¿Qué le dije al espejo esta mañana? Gracias por no romperte al verme.",
    "¿Por qué no voy de fiesta? Porque ya tengo suficiente ruido en mi cabeza.",
    "¿Qué es lo peor de ser un chiste andante? Que nadie se ríe.",
    "¿Por qué no hablo con la almohada? Porque ya tiene suficiente con mis lágrimas nocturnas.",
    "¿Qué le dice una persona triste a la felicidad? Nos vemos... pero nunca en mi casa.",
    "¿Por qué el sol me evita? Porque siempre estoy bajo una nube.",
    "¿Qué hace un corazón roto? Se convierte en un rompecabezas... y yo ya perdí las piezas.",
    "¿Qué le dice la tristeza a la alegría? Qué suerte tienes de ser invitada a las fiestas.",
    "¿Por qué no uso paraguas? Porque la lluvia y yo lloramos en sincronía.",
    "¿Por qué no miro al cielo? Porque las estrellas me recuerdan que estoy muy, muy lejos de brillar.",
    "El café estaba tan fuerte que ahora levanta pesas.",
    "Me compré un mapa para no perder la paciencia, pero lo perdí.",
    "Pinté un pez en la pared y ahora nada en el pasillo.",
    "El panadero dejó su trabajo porque su plan no tenía miga.",
    "Un caracol cruzó la carretera y ahora tiene una multa por exceso de lentitud.",
    "Me caí con estilo... pero nadie aplaudió.",
    "Los tomates se pusieron rojos porque escucharon un chiste picante.",
    "Encendí una vela y ahora no quiere apagarse, dice que está en su mejor momento.",
    "El sol estaba tan cansado que se tomó un día libre y dejó todo nublado.",
    "El lápiz se quebró por estrés, estaba bajo mucha presión.",
    "El papel se rebeló y ahora vive arrugado por decisión propia.",
    "La lámpara se apagó porque quería descansar de iluminar problemas.",
    "El reloj dejó de funcionar porque ya no tenía tiempo para tonterías.",
    "Me comí una galleta y ahora estoy esperando que me dé las gracias por disfrutarla.",
    "La mesa se enojó porque siempre la usan como apoyo emocional.",
    "El ventilador se mareó de tanto girar y pidió vacaciones.",
    "Mi teléfono no me habla desde que lo dejé caer al suelo.",
    "El coco dejó de ser loco porque fue a terapia.",
    "El espejo me dijo: Hoy estás muy bien... pero luego se rompió de la risa."
]

function getChisteMaloRandom(){
    return chistesMalos[getRandomInt(chistesMalos.length-1)]
}