const frasesFrida = [
    "Pies, ¿para qué los quiero si tengo alas para volar?",
    "Soy mi propia musa. Soy el sujeto que conozco mejor.",
    "La vida es un conjunto de experiencias, y yo he vivido muchas.",
    "No quiero ser una mujer perfecta, solo quiero ser yo misma.",
    "El dolor es parte de la vida, pero no debe definirnos.",
    "La pintura es una forma de vida, una forma de expresarme.",
    "Mis heridas son parte de mi belleza.",
    "El amor y el dolor son inseparables.",
    "Cada día es una nueva oportunidad para ser feliz.",
    "Mi vida es mi obra de arte.",
    "Las cosas que me duelen me hacen más fuerte.",
    "La autenticidad es la clave de la felicidad.",
    "Vivo en un mundo de sueños y fantasías.",
    "No hay nada más hermoso que ser uno mismo.",
    "La creatividad es un acto de resistencia.",
    "Amo la vida, a pesar de sus dificultades.",
    "La fragilidad y la fortaleza pueden coexistir en una misma persona.",
    "El arte es el refugio de mi alma.",
    "No hay límites para la imaginación.",
    "La belleza se encuentra en las imperfecciones.",
    "Siempre he sido un espíritu libre.",
    "Mis pinturas son un espejo de mi vida.",
    "La vida es un viaje, no un destino.",
    "Nunca te rindas, sigue luchando por tus sueños.",
    "La pasión es el motor de mi existencia.",
    "El amor verdadero es un acto de valentía.",
    "La soledad puede ser un gran maestro.",
    "Los colores son la música de mis emociones.",
    "La vida me ha enseñado a ser resiliente.",
    "A veces, el silencio habla más que las palabras.",
    "No hay nada más poderoso que una mujer que se ama a sí misma.",
    "La adversidad me ha hecho quien soy.",
    "El arte puede sanar las heridas del alma.",
    "El sufrimiento es parte de la experiencia humana.",
    "Mis raíces son mi fuerza.",
    "El tiempo no cura, solo enseña a vivir con el dolor.",
    "Soy un rompecabezas de emociones y experiencias.",
    "La libertad es un estado del ser.",
    "La vida es un lienzo en blanco, y yo elijo los colores.",
    "Cada cicatriz cuenta una historia.",
    "La risa es un acto de rebeldía.",
    "Mis sueños son mi refugio.",
    "El arte no tiene reglas, solo emociones.",
    "La historia de mi vida es mi mayor inspiración.",
    "La lucha es el camino hacia la libertad.",
    "No hay nada más liberador que ser auténtico.",
    "El amor puede ser un doloroso desafío.",
    "Las flores son mis compañeras en la tristeza.",
    "Vivo para crear y crear para vivir.",
    "El espíritu humano es indomable.",
    "Mis pinturas son mis autobiografías.",
    "El arte me permite expresar lo que las palabras no pueden.",
    "Cada cuadro es una ventana a mi alma.",
    "Pinto mi realidad, no lo que otros ven.",
    "Mis pinceles son mis aliados en la lucha contra el dolor.",
    "El color es la música que siento en mi corazón.",
    "Mis obras son un reflejo de mis emociones más profundas.",
    "El arte es mi refugio y mi rebelión.",
    "Pinto para liberarme de mis cadenas.",
    "Cada trazo es un grito de mi ser.",
    "Mis cuadros son una conversación con el mundo.",
    "El surrealismo es mi forma de ver la vida.",
    "El dolor se transforma en belleza a través de la pintura.",
    "Mis autorretratos son un espejo de mi identidad.",
    "La naturaleza es una fuente infinita de inspiración.",
    "Mis obras son un testimonio de mi resistencia.",
    "Pintar es un acto de amor hacia mí misma.",
    "El arte me permite sanar mis heridas.",
    "Cada pintura es un viaje a mi interior.",
    "Mis raíces culturales son el alma de mi arte.",
    "El arte es una forma de entender el sufrimiento.",
    "Mis colores son la expresión de mis emociones.",
    "Pinto lo que siento, no lo que veo.",
    "La vida y el arte son inseparables en mi mundo.",
    "Mis obras son un diálogo entre el dolor y la alegría.",
    "Cada cuadro cuenta una historia que necesita ser contada.",
    "El arte es mi forma de resistencia.",
    "Mis pinceladas son mis pensamientos más íntimos.",
    "Pinto para recordar y para olvidar.",
    "El arte es la forma más pura de la verdad.",
    "Mis imágenes son un reflejo de mis luchas.",
    "La belleza y el dolor coexisten en cada obra.",
    "Mis pinturas son fragmentos de mi vida.",
    "El arte me da voz en un mundo que a menudo me silencia.",
    "Pintar es un viaje de autodescubrimiento.",
    "Cada obra es un grito de mi corazón.",
    "Mis autorretratos son un diálogo constante conmigo misma.",
    "El arte es mi manera de desafiar las normas.",
    "Mis obras son un canto a la vida y a la muerte.",
    "Pinto para conectar con lo que me rodea.",
    "El arte es una forma de explorar mi identidad.",
    "Mis pinturas son un homenaje a mis raíces.",
    "La vulnerabilidad es el corazón de mi arte.",
    "Cada color tiene su propio significado en mi obra.",
    "Mis cuadros son un reflejo de mis pasiones.",
    "El arte se convierte en mi voz cuando el silencio es abrumador.",
    "Pinto para desafiar las expectativas.",
    "Mis obras son una celebración de la dualidad de la vida.",
    "El arte es mi forma de resistir y persistir.",
    "Cada trazo es un acto de amor hacia mi historia.",
    "La vida es un constante juego de contrastes.",
    "No pinto lo que veo, pinto lo que siento.",
    "Soy mi propia musa. Soy el tema que conozco mejor.",
    "La tristeza es un muro entre dos jardines.",
    "Vivo en mis propias contradicciones.",
    "El dolor es parte de la vida, y la vida es un arte.",
    "Cada día es un nuevo comienzo.",
    "Mis heridas son mi fortaleza.",
    "El amor es un viaje que nunca termina.",
    "La creatividad surge del sufrimiento.",
    "A veces, me siento perdida, pero siempre encuentro el camino.",
    "La autenticidad es mi mejor ropa.",
    "No hay nada más bello que ser uno mismo.",
    "El arte es la forma de liberarse del dolor.",
    "La vida me ha enseñado a ser fuerte.",
    "El sufrimiento puede ser un gran maestro.",
    "La belleza es efímera, pero el arte es eterno.",
    "No me arrepiento de mis elecciones, son parte de mí.",
    "El amor y el dolor son dos caras de la misma moneda.",
    "tengo un pasado muy oscuro",
    "mi visión es profunda sobre la vida, el amor y el arte."

]

function getFraseFridaRandom(){
    return frasesFrida[getRandomInt(frasesFrida.length-1)]
}