const frasesLocura = [
    "Pies, ¿para qué los quiero si tengo alas para volar?",
    "La locura es como un espejo, te muestra lo que realmente eres.",
    "En mis sueños, siempre soy libre.",
    "La vida sin amor es como un árbol sin flores.",
    "Mis heridas son mi fuerza, son mi voz.",
    "Soy una mujer que se siente como un león en una jaula.",
    "A veces, creo que soy dos: una que ama y otra que teme.",
    "La tristeza es un estado de ánimo, pero la locura es un arte.",
    "Vivo en un mundo donde el dolor y la belleza son uno.",
    "La vida es un juego de locura y pasión.",
    "Soy mi propia musa, mi locura es mi inspiración.",
    "La realidad es solo una ilusión que yo elijo romper.",
    "La locura es un refugio para los que se sienten diferentes.",
    "Mis pensamientos son como mariposas: bellos, pero impredecibles.",
    "Desnudar mi alma es mi forma de ser libre.",
    "El caos en mi mente es el arte en mi lienzo.",
    "La vida me duele, pero también me enseña a amar.",
    "Mis lágrimas son pinceladas de color en mi vida.",
    "El dolor es temporal, pero la locura es eterna.",
    "Cada día es una batalla entre la razón y la locura en mi corazón.",
    "Soy la tormenta y la calma, todo en uno.",
    "Las cicatrices son la historia de mi vida escrita en mi piel.",
    "En mi locura, encuentro la claridad que el mundo ignora.",
    "El arte es mi forma de gritar sin ser escuchada.",
    "Los sueños son el refugio de mis locuras.",
    "La belleza y el dolor son mis eternos compañeros.",
    "A veces, me pierdo en el laberinto de mis pensamientos.",
    "La pasión es un fuego que consume mi locura.",
    "Mis colores son gritos de lo que llevo dentro.",
    "El amor es un acto de locura que vale la pena.",
    "La vida es un lienzo, y yo soy la pintora de mis locuras.",
    "Cada lágrima es un trazo de mi historia.",
    "La locura es una danza en la que todos somos bailarines.",
    "Las sombras de mi mente son mis mejores aliadas.",
    "Soy un rompecabezas de emociones, siempre incompleta.",
    "La libertad es un estado de locura que busco.",
    "Mis pensamientos son ríos caudalosos que fluyen sin control.",
    "La vida es un sueño, y yo soy su más loca soñadora.",
    "En la locura, encuentro la esencia de la vida.",
    "Soy un espejo roto que refleja la belleza del caos.",
    "Estoy en forma... redonda es una forma, ¿no?",
    "Mis ideas son como mi cabello: a veces un poco enredadas.",
    "Soy multitasking: puedo desordenar la casa y comer al mismo tiempo.",
    "La locura es solo un estado de ánimo… y el mío es festivo.",
    "Si la vida te da limones, ¡haz limonada y añádele vodka!",
    "No estoy loca, solo tengo una imaginación muy activa.",
    "Soy como un rompecabezas: a veces falta una pieza… o muchas.",
    "¿Quién necesita un plan? La locura es mi GPS.",
    "Soy la reina de la procrastinación, ¡y tengo un trono de almohadas!",
    "La vida es corta, así que ríe mientras tengas dientes.",
    "Mis plantas son mis mejores amigas… nunca me juzgan.",
    "Soy un desastre, pero un desastre fabuloso.",
    "La razón por la que no hago ejercicio es porque no puedo encontrar mis zapatillas.",
    "Mi espíritu animal es un unicornio… en un día de spa.",
    "Siempre sigo mi corazón… y a veces me lleva a la nevera.",
    "Soy como el Wi-Fi: a veces no puedo conectar.",
    "¿Planificar? No, gracias. Prefiero la aventura de lo inesperado.",
    "Me encanta el silencio… ¡pero solo en mi cabeza!",
    "No tengo problemas, solo situaciones de alto entretenimiento.",
    "El chocolate es mi terapia, y soy una adicta a la sanación.",
    "No necesito un príncipe, solo pizza y una buena serie.",
    "Soy tan especial que incluso mis locuras tienen locuras.",
    "La vida es como un chiste: si no te ríes, es porque no lo entendiste.",
    "Mis ideas son como mis calcetines: a veces están desparejadas.",
    "No estoy hablando sola, solo estoy teniendo una reunión.",
    "Soy la única persona que puede hacer un desastre en una tienda de dulces.",
    "La locura es solo creatividad sin límites.",
    "Si pudiera ser cualquier cosa, sería un sofá… cómodo y siempre ocupado.",
    "Soy un paquete de sorpresas… y a veces, un paquete de papas fritas.",
    "Mi vida es como un reality show… sin las cámaras.",
    "La risa es el mejor remedio, y yo tengo una farmacia.",
    "No soy desorganizada, simplemente tengo un estilo único.",
    "Hoy decidí ser normal… pero eso es muy aburrido.",
    "Mis ideas son como burbujas: brillantes y a veces explotan.",
    "Soy la prueba de que la locura puede ser divertida.",
    "No tengo un plan de vida, solo una lista de cosas que no debo hacer.",
    "Si no puedo reírme de mí misma, entonces, ¿quién lo hará?",
    "La vida es un juego, y yo soy la jugadora más loca.",
    "Amo la lluvia… porque no se ve mi pelo despeinado.",
    "Soy un rompecabezas con muchas piezas perdidas.",
    "Me dicen que soy un poco loca, pero prefiero ser única.",
    "Soy un caos organizado… o un desastre bien intencionado.",
    "Mis sueños son tan grandes que a veces no caben en mi cabeza.",
    "La locura es solo otra forma de ser genial.",
    "Si el café no me despierta, entonces la locura lo hará.",
    "Soy la reina del '¿qué estaba haciendo?'",
    "La vida es como un burrito: a veces se desarma, pero sigue siendo deliciosa.",
    "No tengo una crisis de los 30, tengo una fiesta de los 30.",
    "La locura es mi superpoder… ¡y lo uso a diario!",
    "Soy como un reloj roto: siempre estoy en hora… para el caos.",
    "Mis cejas son alas de cuervo que vuelan hacia el abismo de mi alma rota.",
    "Pinto flores en mis venas para que la sangre baile como tequila en la noche.",
    "Diego, mi elefante, ¿por qué no te conviertes en mariposa y vuelas de mi jaula?",
    "El dolor es un mono que trepa por mi columna vertebral, gritando secretos al viento.",
    "Mis piernas son raíces de maguey, clavadas en la tierra que me devora viva.",
    "Amo como un volcán en erupción, quemando todo a mi paso con lava de pasión.",
    "En mis sueños, soy un ciervo herido que corre hacia el sol sangriento.",
    "La muerte me coquetea con calaveras de azúcar, pero yo le respondo con pinceladas furiosas.",
    "Mi corsé es una armadura de espinas, protegiendo un corazón que late como tambor de guerra.",
    "Pinto autorretratos para que mis demonios posen y dejen de atormentarme.",
    "El amor es un accidente de tren que me deja hecha trizas, pero sigo pintando.",
    "Mis lágrimas son ríos de colores que inundan el lienzo de mi existencia.",
    "Diego, eres mi traición favorita, un mural de mentiras que adoro odiar.",
    "Vivo en un jardín de espinas donde las rosas sangran y las mariposas mueren.",
    "Mi cuerpo es un lienzo roto, pero mi espíritu pinta estrellas en la oscuridad.",
    "Bailo con la muerte en una fiesta de Día de Muertos, con tequila y calaveras.",
    "Mis cejas se unen en un puente hacia la locura, cruzando ríos de delirio.",
    "El dolor me hace volar, como un pájaro con alas de fuego y plumas de agonía.",
    "Amo a México como a un amante infiel, con sus colores que me traicionan y embriagan.",
    "Pinto monos en mi mente para que cuiden mis secretos más salvajes.",
    "Mi corazón es una piñata rota, derramando dulces amargos al golpe del destino.",
    "Diego, ¿por qué no te conviertes en flor y te marchitas en mi jarrón de celos?",
    "El accidente me convirtió en mosaico, piezas de mí esparcidas en el caos.",
    "Sueño con ser un jaguar que devora la luna y escupe estrellas.",
    "Mis venas son ríos de tinta, escribiendo poemas en la piel de la tierra.",
    "La pasión es un incendio forestal que quema mis huesos y renace mis alas.",
    "Pinto espinas en mi corona, reina de un reino de dolor exquisito.",
    "Diego, mi traidor, bailas en mis sueños como un toro enloquecido.",
    "Mi alma es un caleidoscopio de colores rotos, girando en la eternidad.",
    "Vivo entre monos y flores, guardianes de mi locura florida.",
    "El amor me apuñala como un cuchillo de obsidiana, pero sangro arte.",
    "Mis ojos son espejos que reflejan tormentas de pasión contenida.",
    "Bailo con fantasmas en mi cama de hospital, riendo ante la muerte.",
    "Pinto mi útero como un nido vacío, lleno de huevos de sueños rotos.",
    "Diego, eres mi veneno dulce, un trago que me mata y revive.",
    "Mi vida es un carnaval de máscaras, donde el dolor se disfraza de alegría.",
    "Las mariposas en mi estómago son en realidad murciélagos de deseo.",
    "Pinto calaveras sonrientes para burlarme de la parca que me acecha.",
    "Mi columna es un árbol torcido, sosteniendo frutos de agonía madura.",
    "Amo como un huracán, destruyendo todo para renacer en calma.",
    "En mis venas corre sangre de tequila y tinta, embriagando mi arte.",
    "Diego, mi elefante pintor, ¿por qué no te encoges en mi bolsillo de celos?",
    "Sueño con ser un río que fluye hacia el mar de la eternidad loca.",
    "Mis cejas son arcos de triunfo sobre el campo de batalla de mi rostro.",
    "El dolor es mi musa, una amante cruel que me inspira genialidad.",
    "Pinto monos guardianes para que vigilen mis noches de insomnio.",
    "Mi corazón late al ritmo de un mariachi enloquecido por el amor.",
    "Vivo en un mundo donde las flores sangran y las espinas cantan.",
    "Diego, eres mi mural viviente, lleno de grietas y colores traidores.",
    "Mi cuerpo es una ruina azteca, habitada por dioses de locura.",
    "Bailo sobre el abismo, con zapatos de fuego y falda de estrellas.",
    "Pinto mi alma en fragmentos, como un rompecabezas de delirios.",
    "El amor es un veneno que bebo con gusto, en copas de cristal roto.",
    "Mis lágrimas fertilizan jardines de espinas, donde crecen rosas negras.",
    "Diego, mi traición andante, bailas en mis venas como un virus apasionado.",
    "Sueño con alas de mariposa, pero vuelo con plumas de cuervo herido.",
    "Mi vida es un lienzo en blanco que lleno con manchas de caos colorido.",
    "Pinto la muerte como una amiga coqueta, con labios rojos y ojos vacíos.",
    "Mi espíritu es un volcán dormido, listo para erupcionar en arte furioso.",
    "Vivo loca, pinto loca, amo loca: así es Frida, eterna en su delirio."
]

function getFraseLocuraRandom(){
    return frasesLocura[getRandomInt(frasesLocura.length-1)]
}