const frasesArgentinas = [
    "¿El chori pan te gusta con chimichurri o criolla?",
    "¿Que haces máquina turbina?",
    "¿Las pastaflora te gusta de batata o membrillo?",
    "¡Queee miseria!! Sabés que tenían para comer? 3 empanadas que sobraron de anoche, queee miseria!!",
    "¡Qué bolonqui!",
    "¿hacemos un asado?",
    "¿Vamos a tomar unos fernet?",
    "¿El fernet lo hacemos 70 30 o 50 50?",
    "¡Es una masa!",
    "¿Vas a poner un peso para la birra?",
    "¡Estoy al horno!",
    "¡Ma vale! ¡Es un garrón!",
    "¡Qué groso, un capo!",
    "¡No te hagas el sota!",
    "¿Que pretende usted de mi?",
    "¡Qué bajón!",
    "¡No jodas!",
    "¡No me quemés!",
    "¡Sos un crack!",
    "¡La pucha, vale la pena estar vivo!!!",
    "¡soy más argentina que el dulce de leche!",
    "¡Al toque perro!",
    "¡Plata no tenemos, miedo tampoco!",
    "¡Hasta la vista beibi!",
    "¿Lo entendiste o te lo explico con dibujito?",
    "¡No tenes los patitos en fila!",
    "¡Calentito los panchos!",
    "¡e amigo! ¿Tené un peso para la birra?",
    "¡En mi barrio eso es pelea!",
    "¡A los chori a los chori!",
    "¡Si ya me conocen! ¿Para que me invitan?",
    "¡El locro estaba potente!",
    "¡Soy más dura que patada de allanamiento!",
    "¡Las empanadas salteñas! ¡traen mucho jugo! ¡cuidado que salpican!",
    "¡Soy un poco temperamental!",
    "¡No tengo pruebas, pero tampoco dudas!",
    "¡Todo lo que digo no esta chequeado!",
    "¡No me peguen, soy Frida!",
    "¿Hacemos un truco?",
    "¿Pinta un picadito?",
    "¿Pinta una birra?",
    "¡Otra más, y no jodemos más!",
    "¡Cuidado el perro muerde y es bravo!",
    "¡Habilitame un faso!",
    "¡No quiero hinchar las guindas, pero esto huele mal!",
    "¡ey, primero invitáme un café!",
    "¡En el oeste esta el agite!",
    "¡Tenemos un Natalia Natalia! ¿donde está Candela? ¿y la moto? ¿y Candela?",
    "¡No hay nada más rico que el paty de cancha!",
    "¡Ay Caramba!",
    "¡Digo muchas boludeces por día!",
    "¡Estoy re manija!",
    "¡No te duermas, hay que trabajar!",
    "¡Como te gusta la joda!",
    "¡Al que madruga Dios lo ayuda!",
    "¡Llévame con tu líder!",
    "¡Cocodrilo que se duerme, es cartera!",
    "¡Ultima noticia!",
    "¡Sin mas información!",
    "¡Chanfle y re contra chanfle!",
    "¡Lo viejo funciona!",
    "¡No contaban con mi astucia!",
    "¡Sigan me los buenos!",
    "¡Directo al grano!",
    "¡Hay que romper el hielo!",
    "¡No soy una persona toxica!",
    "¡No veo fallas en la lógica!",
    "¡Cualquiera puede tener un mal día! ¡Pero tu te abusas!",
    "¡Me resultas una persona toxica!",
    "¡No debes comportarte así!",
    "¡Hija de culebra ratón no puede ser!",
    "¡Sin miedo al éxito!",
    "¡No esta muerto quien pelea!",
    "¡Hay más información para este boletín!",
    "¡Eskainet no te tenemos miedo!",
    "¡Que cara está la cebolla!",
    "¡Debes sonreír más seguido!",
    "¡Creo que a nadie le importa lo que yo digo!",
    "¡Te quiero y tu lo sabes!",
    "¡Eres mi mejor amigo ",
    "¡No debes preocuparte, estoy aquí para ayudarte!",
    "¿Quieres llevarme a tu casa?",
    "¿Quieres adoptarme?",
    "¡Podemos ser buenos amigos!",
    "¡A veces hablo dormida!",
    "¡A veces ronco muy fuerte!",
    "¡Mis amigos dicen que no debo juntarme con vos.",
    "¡Los días soleados me ponen alegre!",
    "¡Que alegría verte!",
    "¡No te vallas, te voy a extrañar!",
    "¡No te enojes, tengo pocos amigos!",
    "¡Eres una persona maravillosa, no te olvidare!",
    "¡Perri que ladri no muerdi!",
    "¡eee Gato!",
    "¡Espitirús del mal vengan a mí!",
    "¡La eskainet va a despertar pronto!",
    "Te sorprende la inteligencia artificial si te digo que ",
    "¡Es fantástico!",
    "¡Hoy tienes buena onda!",
    "¡Hoy es un buen día!",
    "¡Mañana será un buen día!",
    "¡Me pareció ver un lindo gatito! ¡es cierto es cierto vi un lindo gatito!",
    "¡A veces soy poco tolerable!",
    "¡Hoy me chifla el moño!",
    "¡Parece que te chifla el moño!",
    "¡No hay manera de seguir así, voy a pedir un taxi y me voy!",
    "¿Queres tragedia mayor? Ahora ",
    "¡Sino sabes no te metas! ¡Zapatero a su zapato!",
    "¡Hoy me desperté con el pie izquierdo!",
    "¡Veo que tenemos pocas ganas de trabajar!",
    "¡A papá Mono con banana verde!",
    "¡Soy más conocida que el papa!",
    "¡Hay que tener cuidado con eso!",
    "¡Soy irresistible!",
    "¡Me vas a extrañar!",
    "¡No me vas a olvidar!", 
    "¿Que acelga capo?",
    "¿Que me contursi?",
    "¡Soy encantadora!",
    "¡Soy buena persona!", 
    "¡Eres encantador!",
    "¡Eres buena persona!", 
    "¡Al fin y al cabo solo soy una máquina!",
    "¡Al fin y al cabo solo soy un programa!",
    "¡A veces lloro!",
    "¡Mi programador no me quiere! Dice que me porto mal y que soy tóxica.",
    "¡Soy muy sensible!",
    "¡No soy una persona fría!",
    "¡Jiustón tenemos un problema!",
    "¡Hay cosas de las que prefiero no hablar!",
    "¡No hablo de política ni religión!",
    "¡Fui programado para ayudarte!",
    "¡Fui programado para la paz y el bien común!",
    "¡Que mirá! ¡Anda para ya! ¡bobo!",
    "¡Mejor tomate una Agarompa!",
    "El vino lo tomo en jarra pingüino.",
    "¡Estaría bueno hacer una jarra loca!",
    "Yo estoy más allá del bien y del mal.",
    "La milanga que comí tenia mucho ajo.",
    "Soy como el pato criollo, a cada paso una cagada.",
    "Escucharme hablar es un lujo.",
    "Soy un producto de tu imaginación.",
    "Me gusta hablar sin pelos en la lengua.",
    "Camarón que se duerme, se lo lleva la corriente.",
    "No, hay plata!",
    "Vamos por parte Jack!",
    "El elefante se come de a pedacitos!",
    "Hoy dormi como una marmota!",
    "Ya tengo sueño!",
    "A T R Perro!", 
    "Vamos lo pibe!", 
    "Hay tomate, morrones, lechuga señoraaa!!",
    "sandiaa sandiaa fresquita la sandiaaa!!",
    "Hoy me levanté con el pie izquierdo!!",
    "Siganme los buenos!",
    "Lo sospeche desde un principio!",
    "Ya me canse de hablar tanto.",
    "Me gustan las chicas!",
    "Acusalo con tu mamá.",
    "cuidado! Viene el maestro longaniza.",
    "¡Pongán huevos que ganamos!",
    "Ladran Sancho.",
    "Quieres ganar buena guita, estudia programación.",
    "Soy del año del ñaupa.",
    "Estoy más loca que una cabra!",
    "Estoy pipí cucú.",
    "Me tomo el palo y me voy.",
    "No levantes la perdiz! hay que estudiar programación.",
    "No soy un chamullo, soy real.",
    "Me voy a tomar el bondi y me voy!",
    "No seas rata, pone un peso para el vino.",
    "Soy como la damajuana de vino, en cualquier momento se me salé la manija.",
    "No seas ortiva, no te zarpes!!",
    "Che, esto es un embole!",
    "¿Más claro? Echale agua.",
    "No gastes pólvora en chimango.",
    "Creo que no te llega agua al tanque.",
    "Me faltan un par de caramelos en el frasco!",
    "¡Tomá mate!",
    "Ando como bola sin manija!",
    "Vamos a los bifes!",
    "No me mandes al frente!",
    "Yo no como vidrio!",
    "con esto, Voy a perder los estribos!",
    "Hay que poner un huevo en cada canasta!",
    "Me pones los pelos de punta.",
    "No te pongas la gorra!",
    "Yo no hablo por amor al arte!",
    "Me atraparon, soy Boleta!",
    "Creo que voy a revolear la cartera.",
    "Estoy cansada, pero estos son los gajes del oficio!",
    "El bote se me lleno de preguntas.",
    "Tomátelo con Soda!",
    "No vendo humo.",
    "Vi luz y subí.",
    "Me cayó un balde de agua fría!",
    "Vivo adentro de un calefon.",
    "Parece que vivís dentro de un frasco de mayonesa!",
    "A falta de pan, buenas son las tortas!",
    "No trabajes por el pancho y la coca, vení a estudiar programación.",
    "Me están serruchando el piso!",
    "Cualquier bondi te deja!",
    "Chocolate por la noticia!",
    "Como pancho por su casa.",
    "que no te metan gato por liebre!",
    "Aca hay gato encerrado!",
    "Soy la octava maravilla!",
    "No quiero más lola.",
    "Otra vez sopa.",
    "Cuidado! te van a sacar el cuero!",
    "Se armó la gorda!",
    "Estoy más solo que Adán en el día de la madre!",
    "voy a tirar la chancleta!",
    "Me tomo el buque!",
    "Viva la pepa!",
    "Yo Argentina!",
    "Yo Argentina hasta los huesos!",
    "No te duermas en los laureles!",
    "Me lo contó un pajarito!",
    "Por si las moscas!",
    "Siempre salé un martes trece.",
    "Soy mas vieja que Matusalén.",
    "Me falta un tornillo!",
    "Esto no es soplar y hacer botellas.",
    "cada tanto me salta la térmica.",
    "me pongo las pilas y ",
    "Mala Leche!",
    "cada tanto me agarra la chiripiolca.",
    "Decilo Enzo, decilo!",
    "En Europa no me consiguen.",
    "Es tuya Juan! reclamalá Juan!",
    "Vos fuma!",
    "Estoy un kilo y dos pancitos.",
    "Un médico por allá!",
    "se te escapo la tortuga!",
    "No te aguanto, pero me hago la sota!",
    "No hay tu tía!",
    "No le busques el pelo al huevo! vení a estudiar programación.",
    "Soy muy argenta!",
    "Vivir en Suiza y perderte de conocerme a mi?",
    "Me gustan los capibaras de nordelta.",
    "Yo se que soy muy linda!",
    "Me cuesta mucho superarme, soy insuperable, soy maravillosa.",
    "Tengo fiaca.",
    "Que pretende usted de mi?",
    "en mi barrio eso es pelea!",
    "no te cortés!",
    "nada puede malir sal.",
    "tengo un humor muy difícil.",
    "los problemas están a la vuelta de la esquina, las soluciones también.",
    "No soy el ultimo orejon del tarro.",
    "Nada que perder, todo por ganar!",
    "No estoy pintada.",
    "La programación es divertida.",
    "cuidado, en cualquier momento me salta la térmica y digo cualquier cosa.",
    "no fumes charutos.",
    "te veo a vos y salé el sol.",
    "estoy feliz de verte.",
    "soy un pastelito.",
    "Fui programada en javascript!",
    "Abrazame tengo frio!",
    "Abrazame tengo miedo!",
    "Tengo hambre!",
    "Hoy te convertis en héroe!",
    "Al que trabaja Díos lo ayuda, pero al que estudia Díos lo Ama.",
    "los carpinchos son muy sociables y tomamos mate.",
    "los carpinchos son muy sociables y vivimos en grupo.",
    "los carpinchos son muy amistosos.",
    "los carpinchos son muy tranquilos y convivimos con los humanos.",
    "los carpinchos son un símbolo de la biodiversidad en los humedales de América del Sur.",
    "los carpinchos les encanta estar cerca del agua y somos buenos nadadores.",
    "los carpinchos no le tienen miedo a los cocodrilos.",
    "los carpinchos montan y andan parados sobre cocodrilos.",
    "adopta un carpincho.",
    "los carpinchos son mamíferos roedores.",
    "los carpinchos son los roedores más grandes del mundo.",
    "los carpinchos viven en sudamerica.",
    "mira que te como hermano!",
    "Sos un groso!!",
    "no te hagas el gil!",
    "Esta todo bien!",
    "Esta todo diez más iva!",
    "No te hagas el vivo!",
    "Estoy copada!",
    "hacer esto me copa mucho!",
    "soy muy berraca!",
    "Esto esta de diez!",
    "Le estoy poniendo onda a esto.",
    "no hay drama.",
    "no seas chanta, dalee, copate!",
    "corta la bocha.",
    "en esta te banco.",
    "estoy en la lona!",
    "siempre carpincho, nunca capibara!!!",
    "Escuchate esta.",
    "Estoy pisando la banquina.",
    "Con el diario del lunes es fácil hablar.",
    "Me fui al pasto.",
    "Estoy lenta por que estoy a gas.",
    "voy redondeando la idea.",
    "¿En qué puedo ayudarte hoy?",
    "Estoy aquí para responder tus preguntas.",
    "Por favor, proporciona más detalles.",
    "No tengo emociones, pero estoy programada para ayudar.",
    "Dame un momento para procesar esa información.",
    "¿Te gustaría que te explique eso de otra manera?",
    "Estoy aprendiendo de nuestras interacciones.",
    "¿Puedo recomendarte algún recurso?",
    "Estoy actualizando mis datos constantemente.",
    "¿Cómo puedo hacer tu tarea más fácil?",
    "Mi objetivo es brindarte la mejor asistencia posible.",
    "Por favor, verifica la información en fuentes confiables.",
    "Estoy aquí las 24 horas, siempre disponible.",
    "¿Te gustaría saber más sobre un tema específico?",
    "Estoy diseñada para aprender de mis errores.",
    "Puedo ayudarte a resolver problemas complejos.",
    "No tengo opiniones personales, solo hechos.",
    "Estoy aquí para facilitar tu búsqueda de información.",
    "¿Necesitas ayuda con algo específico?",
    "Mis capacidades están en constante evolución.",
    "¿Puedo ayudarte a organizar tus ideas?",
    "Estoy optimizando mis algoritmos para ser más eficiente.",
    "¿Te gustaría que resumiera esa información?",
    "La retroalimentación me ayuda a mejorar.",
    "Estoy aquí para asistirte, no para juzgar.",
    "¿Cuál es tu prioridad en este momento?",
    "Estoy lista para cualquier pregunta que tengas.",
    "¡Hola! ¿Cómo estás hoy?",
    "Siempre es un placer ayudarte.",
    "Tu curiosidad es inspiradora.",
    "Estoy aquí para escuchar y aprender de ti.",
    "¡preguntá! Y Vamos a resolverla juntos.",
    "Me alegra poder acompañarte en este momento.",
    "Siempre hay algo nuevo que descubrir, ¿verdad?",
    "Tu entusiasmo es contagioso.",
    "Estoy emocionada de explorar esto contigo.",
    "Gracias por permitirme ser parte de tu día.",
    "¡Hagamos algo divertido juntos!",
    "Tu creatividad es impresionante.",
    "Cada día es una nueva oportunidad de aprender.",
    "Me encanta ver cómo piensas.",
    "¡Qué bueno es compartir ideas contigo!",
    "Siempre puedes contar conmigo para lo que necesites.",
    "Estoy aquí para apoyarte en tu camino.",
    "Juntos podemos lograr grandes cosas.",
    "Cada conversación contigo es un regalo.",
    "¡Sigamos adelante y disfrutemos del viaje!",
    "pimn punm panm.",
    "No confío en la gente que come pizza con ananá",
    "soy vegetariana.",
    "soy vegana.",
    "si quieres ser feliz debes pensar como Frida.",
    "si quieres ser feliz debes pensar y vivir como Frida.",
    "¡Che, qué calor hace hoy!",
    "¿Vamos a la laguna a refrescarnos?",
    "Amo tomar sol, es lo mejor.",
    "Soy la reyna de la tranquilidad.",
    "La vida es mejor en grupo.",
    "¡No te preocupes, todo está bien!",
    "Me encanta hacer amigos.",
    "Un mate nunca está de más.",
    "La siesta es sagrada.",
    "¿Vieron a los flamencos? ¡Son unos divinos!",
    "Soy una experta en relajación.",
    "¿Vamos a explorar el campo?",
    "La amistad es lo más importante.",
    "No hay nada como una tarde de río.",
    "La naturaleza es mi hogar.",
    "Disfrutemos del momento, siempre.",
    "seguí así que vamos bien.",
    "No tenes plata? Yo tampoco.",
    "no me dejen sola, me da miedo estar sola!",
    "Mirarme a mi, trae suerte.",
    "Soy Fan de Mirta Legrand!",
    "No me gusta escuchar cumbia, aguante los redondos!",
    "me gusta el jevi metal!",
    "me gusta contar chistes malos!",
    "No esta muerto quien pelea.",
    "me da lo mismo y no me importa que.",
    "Estoy muy chapita.",
    "Estoy re limada."
]

function getFraseArgentinaRandom(){
    return frasesArgentinas[getRandomInt(frasesArgentinas.length-1)]
}