const frasesEstudios = [
    "¿Té gustaría estudiar Java?",
    "¿Té gustaría estudiar Tester de Aplicaciónes?",
    "¿Té gustaría estudiar Javaescript?",
    "¿Té gustaría estudiar Paiton?",
    "¿Té gustaría estudiar Cyber Seguridad?",
    "¿Té gustaría estudiar Análisis de datos?",
    "¿Té gustaría estudiar Programación Web?",
    "¿Té gustaría estudiar Automatización Industrial.",
    "¿Té gustaría estudiar Mecánica Automotriz.",
    "¿Té gustaría estudiar Mecánica de Motos.",
    "¿Té gustaría estudiar Impresión 3D.",
    "¿Té gustaría estudiar Marketing Digital.",
    "Quieres ganar buena guita, estudia programación.",
    "No levantes la perdiz! hay que estudiar programación.",
    "No trabajes por el pancho y la coca, vení a estudiar programación.",
    "Estudia programación, más vale tarde que nunca!",
    "Nada que perder, todo por ganar!",
    "La programación es divertida.",
    "estudia Marketing digital.",
    "Te gustaría estudiar Marketing digital?",
    "estudia Análisis de datos.",
    "Te gustaría estudiar análisis de datos?",
    "Hacete conocer, estudiá marketing digital.",
    "Convertite en un Bi Ai, estudia análisis de datos.",
    "Domina la inteligencia de negocio con análisis de datos.",
    "Tu vida pide alegría, por eso vení a estudiar con nosotros.",
    "Deberías estudiar energías renovables.",
    "estudia energías renovables.",
    "Contribuye con el medio ambiente, estudia energías renovables.",
    "Te falta un tornillo, imprimilo en 3 d, estudia modelado 3 d.",
    "estudia modelado 3 d.",
    "deberías estudiar modelado 3 d.",
    "estudia reparación de celulares.",
    "deberías estudiar reparación de celulares.",
    "potencia tus ventas con marketing digital.",
    "querés ser famoso como yo, estudia marketing digital.",
    "pronto inician los cursos de reparación de celulares.",
    "se te rompió la pantalla del celular? Estudia reparación de celulares.",
    "se astilló la pantalla del celular? Estudia reparación de celulares.",
    "estudia instalación de alarmas de seguridad.",
    "estudia reparación de equipos de climatización.",
    "estudia reparación de aires acondicionado.",
    "estudia instalación de redes informáticas.",
    "estudia reparación de impresoras 3 D.",
    "estudia electricidad básica.",
    "tenemos cursos con inserción laboral.",
    "Estas aburrido en tu casa? estudia instalación de alarmas de seguridad.",
    "Estas aburrido en tu casa? estudia reparación de equipos de climatización.",
    "Estas aburrido en tu casa? estudia reparación de aires acondicionado.",
    "Estas aburrido en tu casa? estudia instalación de redes informáticas.",
    "Estas aburrido en tu casa? estudia reparación de impresoras 3 D.",
    "Estas aburrido en tu casa? estudia electricidad básica.",
    "Estas aburrido en tu casa? ven a estudiar con nosotros.",
    "tenemos cursos con inserción laboral.",
    "siempre es bueno estudiar.",
    "mejora tus capacidades laborales, estudia con nosotros.",
    "no lo dudes, estudia con nosotros.",
    "En formación profesional, brindamos capacitaciones gratuitas.",
    "no sabes que hacer de tu vida? Vení a estudiar con nosotros.",
    "te sentís solo? Vení a estudiar con nosotros.",
    "tu amor te dejó? Vení a estudiar con nosotros.",
    "estas sin trabajo? Vení a estudiar con nosotros.",
    "estas depre? Vení a estudiar con nosotros y te alegramos el día.",
    "dale a tu vida un cambio, vení a estudiar con nosotros.",
    "ponele fin a los problemas, vení a estudiar con nosotros.",
    "tu moto te deja a pata? estudia reparación de motos.",
    "estas cansado de ir al mecánico? estudia mecánica del automotor.",
    "tenés una moto vieja? estudia reparación de motos.",
    "tenés un auto viejo? estudia mecánica del automotor.",
    "Toda nuestra oferta educativa es gratuita.",
    "Toda nuestra oferta educativa cuenta con certificación oficial de validez nacional.",
    "Otro año sin trabajo? vení a estudiar con nosotros!",
    "tenemos oferta educativa de administración.",
    "tenemos oferta educativa de informática.",
    "tenemos oferta educativa de comunicación y producción audiovisual.",
    "tenemos oferta educativa de construcciones.",
    "tenemos oferta educativa de cuero y calzado.",
    "tenemos oferta educativa de Energía y dispositivos eléctricos.",
    "tenemos oferta educativa de Estetica.",
    "tenemos oferta educativa de Hotelería.",
    "tenemos oferta educativa de Gastronomía.",
    "tenemos oferta educativa de Mecánica automotriz.",
    "tenemos oferta educativa de Turismo.",
    "tenemos oferta educativa de Marroquinería.",
    "tenemos oferta educativa de Carpintería.",
    "potencia tu carrera y asegura tu futuro, estudia con nosotros!",
    "no sabes que hacer? estudia administración.",
    "no sabes que hacer? estudia informática.",
    "no sabes que hacer? estudia producción audiovisual.",
    "no sabes que hacer? estudia construcciones.",
    "no sabes que hacer? estudia Energía y dispositivos eléctricos.",
    "no sabes que hacer? estudia Estetica.",
    "no sabes que hacer? estudia Hotelería.",
    "no sabes que hacer? estudia Gastronomía.",
    "no sabes que hacer? estudia Mecánica automotriz.",
    "no sabes que hacer? estudia Turismo.",
    "no sabes que hacer? estudia Marroquinería.",
    "no sabes que hacer? estudia Carpintería.",
    "Deberías estudiar administración.",
    "Deberías estudiar informática.",
    "Deberías estudiar producción audiovisual.",
    "Deberías estudiar construcciones.",
    "Deberías estudiar Energia y dispositivos eléctricos.",
    "Deberías estudiar Estetica.",
    "Deberías estudiar Hotelería.",
    "Deberías estudiar Gastronomía.",
    "Deberías estudiar Mecánica automotriz.",
    "Deberías estudiar Turismo.",
    "tu amor te dejó? Vení a estudiar administración.",
    "tu amor te dejó? Vení a estudiar informática.",
    "tu amor te dejó? Vení a estudiar producción audiovisual.",
    "tu amor te dejó? Vení a estudiar construcciones.",
    "tu amor te dejó? Vení a estudiar Energia y dispositivos eléctricos.",
    "tu amor te dejó? Vení a estudiar Estetica.",
    "tu amor te dejó? Vení a estudiar Hotelería.",
    "tu amor te dejó? Vení a estudiar Gastronomía.",
    "tu amor te dejó? Vení a estudiar Mecánica automotriz.",
    "tu amor te dejó? Vení a estudiar Turismo.",
    "Hay Centros de Formación Profesional en todos los barrios de CABA.",
    "Busca el centro de estudios más cercano en tu barrio.",
    "nada mejor que aprender oficios.",
    "querés un consejo? aprende un oficio.",
    "querés estudiar en forma gratuita y con certificado oficial?",
    "sabías que podes estudiar en forma gratuita con certificado oficial?",
    "Conoces nuestros centros de formación profesional?",
    "Cual será tu próximo oficio?",
    "construye tu futuro!",
    "Pensaste que oficio deseas aprender?",
    "Cual es tu oficio preferido?",
    "Al que trabaja Díos lo ayuda, pero al que estudia Díos lo Ama.",
    "Queres un oficio, pensate en estudiar para trabajar en la construcción.",
    "Pensaste en estudiar carpintería.",
    "Queres estudiar construcciones con certificado oficial?",
    "veni a formación profesional!",
    "Tu futuro comienza hoy, no mañana. ¡Invierte en tu educación!",
    "Cada lección aprendida es un paso más hacia tus sueños.",
    "El conocimiento es la llave que abre las puertas de las oportunidades.",
    "No te limites. Con esfuerzo y dedicación, puedes alcanzar cualquier meta.",
    "El éxito no es un destino, es un viaje. ¡Únete a nosotros en este camino!",
    "Cada día es una nueva oportunidad para aprender y crecer.",
    "La formación profesional te dará las herramientas para construir tu futuro.",
    "Elige ser la mejor versión de ti mismo. ¡Comienza tu viaje educativo hoy!",
    "La educación transforma vidas. Sé parte de esa transformación.",
    "Cree en ti mismo y en tus capacidades. ¡El futuro es tuyo para conquistarlo!",
    "Domina la tecnología y abre las puertas a un mundo de oportunidades.",
    "Cada código de programación que escribes es un paso hacia el futuro digital.",
    "Conviértete en el arquitecto de la energía que impulsa el mundo.",
    "La electricidad impulsa el progreso. ¡Sé parte de esa revolución!",
    "Haz que cada motor ruede con tu conocimiento y habilidades.",
    "Conviértete en el experto que devuelve la vida a cada vehículo.",
    "Construye tu futuro ladrillo a ladrillo. ¡El cielo es el límite!",
    "Cada edificio que tocas es un legado que dejas.",
    "Crea experiencias inolvidables a través de la hospitalidad.",
    "La cocina es un arte. ¡Conviértete en un maestro de los sabores!",
    "Captura momentos y cuenta historias a través de tu lente.",
    "Tu creatividad puede dar vida a imágenes y sonidos inolvidables.",
    "Transforma la madera en obras maestras con tus propias manos.",
    "Cada herramienta es un aliado en la creación de tu arte.",
    "Descubre el mundo y lleva a otros en esa aventura.",
    "El turismo es la puerta a nuevas culturas y experiencias.",
    "Teje tus sueños con cada hilo que utilizas.",
    "La moda es una forma de expresión. ¡Dale vida a tus ideas!",
    "Realza la belleza y confianza de las personas con tu talento.",
    "Cada transformación es una obra de arte en manos expertas.",
    "Cada oficio es una oportunidad para dejar huella en el mundo.",
    "La pasión y la dedicación son la clave para el éxito en cualquier profesión.",
    "Invierte en tu educación y cosecha los frutos de tu esfuerzo.",
    "La práctica y el aprendizaje constante son tus mejores aliados.",
    "Sé el cambio que deseas ver en tu sector.",
    "Tu futuro está en tus manos. ¡Hazlo brillar!",
    "Cada día es una nueva oportunidad para aprender algo nuevo.",
    "La formación profesional es el primer paso hacia tus sueños.",
    "El trabajo duro y la perseverancia siempre dan frutos.",
    "Cree en ti mismo y en el impacto que puedes tener en el mundo.",
    "Cada oficio es una puerta abierta a nuevas oportunidades.",
    "Aprender un oficio es invertir en tu futuro y en tus sueños.",
    "La habilidad es el mejor camino hacia la independencia y el éxito.",
    "Con cada nuevo conocimiento, te vuelves más valioso en el mundo laboral.",
    "Transforma tus pasiones en habilidades y tus habilidades en una carrera.",
    "No hay límites para lo que puedes lograr si te dedicas a aprender.",
    "Cada día es una nueva oportunidad para dominar un nuevo oficio.",
    "La maestría en un oficio es el resultado de la práctica y la perseverancia.",
    "Cree en ti mismo: puedes convertirte en un experto en cualquier área.",
    "El aprendizaje nunca termina; cada nuevo oficio es un nuevo comienzo.",
    "El conocimiento es el primer paso hacia el crecimiento personal y profesional.",
    "Cada libro que lees es una oportunidad para expandir tu mente y tu vida.",
    "Invertir en ti mismo es la mejor decisión que puedes tomar para tu futuro.",
    "El aprendizaje constante es la clave para desbloquear tu verdadero potencial.",
    "El crecimiento personal comienza cuando te atreves a salir de tu zona de confort.",
    "Desafía tus límites y descubrirás la grandeza que llevas dentro.",
    "Cada día es una nueva oportunidad para aprender y crecer.",
    "El éxito se construye sobre la base del conocimiento y la autoexploración.",
    "Tu mente es un jardín; cultiva el conocimiento y cosecharás sabiduría.",
    "No tenes un mango? nuestra oferta es gratuita.",
    "No tenes un peso? nuestra oferta es gratuita.",
    "No tenes plata? nuestra oferta es gratuita.",
    "El verdadero crecimiento personal comienza cuando te comprometes a mejorar cada día.",
    "La programación es el arte de resolver problemas, y cada línea de código es un paso hacia la solución.",
    "No hay errores, solo oportunidades de aprender. Cada bug es una lección.",
    "La clave del éxito en programación es la perseverancia. Si te caes, levántate y vuelve a intentarlo.",
    "Cada gran programador comenzó como un principiante. ¡Tu viaje apenas está comenzando!",
    "La programación no es solo escribir código, es crear posibilidades.",
    "Los límites de la programación son los límites de tu imaginación. ¡Sueña en grande!",
    "No te compares con otros; cada programador tiene su propio ritmo y estilo.",
    "La práctica constante es el camino hacia la maestría. ¡Código todos los días!",
    "La innovación nace del conocimiento. Cuanto más aprendas, más podrás crear.",
    "Recuerda: cada programa que escribas es un paso hacia el futuro que deseas construir.",
    "El marketing digital es la brújula que guía a las marcas en el vasto océano de la información.",
    "Cada clic es una oportunidad. Aprende a convertir curiosidad en conexión.",
    "La creatividad es tu mejor herramienta. Usa tu imaginación para destacar en el mundo digital.",
    "El éxito en marketing digital no es cuestión de suerte, sino de estrategia y perseverancia.",
    "Aprender de los errores es el primer paso hacia la innovación. No temas experimentar.",
    "En el marketing digital, cada dato cuenta. Conviértete en un maestro de la analítica.",
    "El mundo está en constante cambio. Adáptate, evoluciona y lidera la transformación.",
    "Las mejores campañas nacen de una comprensión profunda de tu audiencia. Escucha y aprende.",
    "No hay límites para lo que puedes lograr. ¡Crea, innova y deja tu huella en el mundo digital!",
    "El marketing digital es un viaje, no un destino. Disfruta cada paso del proceso.",
    "La creatividad no tiene límites; cada impresión 3D es una nueva oportunidad para innovar.",
    "Cada objeto que creas es un paso más hacia el futuro; ¡deja que tu imaginación vuele!",
    "No temas cometer errores; son las impresiones fallidas las que te enseñan a mejorar.",
    "La impresión 3D transforma ideas en realidades; cada proyecto es una historia esperando ser contada.",
    "Con cada capa que imprimes, construyes no solo objetos, sino también tu confianza y habilidades.",
    "El conocimiento es la materia prima; la impresión 3D es el taller donde lo conviertes en algo tangible.",
    "Cada diseño que creas es una huella de tu dedicación; ¡deja una marca en el mundo!",
    "La pasión por aprender es el primer paso hacia la maestría en la impresión 3D.",
    "No hay límites para lo que puedes crear; la única barrera es tu imaginación.",
    "La impresión 3D es el arte de dar vida a tus ideas; ¡no dejes de explorar nuevas posibilidades!",
    "Cada motor que reparas es un desafío superado; ¡cada día es una nueva oportunidad para aprender!",
    "La mecánica automotriz es un arte; con tus manos, puedes hacer que la tecnología cobre vida.",
    "Los problemas son solo oportunidades para encontrar soluciones; cada auto es un rompecabezas esperando ser resuelto.",
    "Dominar la mecánica es como tener el poder de la creación; puedes transformar lo viejo en nuevo.",
    "La pasión por los automóviles es el primer paso; el conocimiento te llevará a la maestría.",
    "Cada herramienta en tu caja es una extensión de tu habilidad; conviértete en un verdadero artista de la mecánica.",
    "No importa cuán complicado sea el problema; con dedicación, cada motor puede volver a rugir.",
    "La mecánica automotriz no solo se trata de reparar; se trata de entender cómo funciona el mundo que nos rodea.",
    "Cada día en el taller es una oportunidad para crecer; ¡nunca dejes de aprender!",
    "Tus manos pueden hacer maravillas; el futuro de la mecánica está en tus manos.",
    "Cada moto que reparas es un viaje hacia el conocimiento; ¡cada desafío es una oportunidad para aprender!",
    "La mecánica de motos es una danza entre precisión y pasión; deja que tu amor por las máquinas te guíe.",
    "Cada pieza que ensamblas te acerca a la maestría; ¡disfruta del proceso de crear y reparar!",
    "Los problemas en la mecánica son solo retos que esperan tu ingenio; cada solución es un triunfo.",
    "La libertad sobre dos ruedas comienza con el conocimiento; conviértete en el experto que siempre soñaste ser.",
    "Cada motor que pones en marcha es un testimonio de tu dedicación; el esfuerzo vale la pena.",
    "La pasión por las motos es el motor de tu aprendizaje; deja que te impulse hacia nuevas habilidades.",
    "Entender la mecánica es como tener el mapa de un emocionante viaje; cada ruta te enseña algo nuevo.",
    "No importa cuántas veces caigas; cada intento es una lección que te acerca a la perfección.",
    "Tu amor por las motos puede transformar el ruido del motor en música; ¡haz que cada reparación cuente!",
    "El futuro pertenece a quienes creen en la belleza de sus sueños.",
    "Cada avance en automatización es un paso hacia un futuro más eficiente.",
    "La clave del éxito es enfocarse en metas, no en obstáculos.",
    "La automatización no reemplaza a los humanos; los libera para ser más creativos.",
    "El conocimiento es el primer paso hacia la innovación.",
    "No temas cometer errores; son parte del aprendizaje en la automatización.",
    "Cada día es una nueva oportunidad para mejorar tus habilidades.",
    "La perseverancia es la madre del éxito en cualquier campo técnico.",
    "La automatización es el arte de hacer más con menos.",
    "Tu esfuerzo hoy es la base de tu éxito mañana."
]

function getFraseEstudioRandom(){
    return frasesEstudios[getRandomInt(frasesEstudios.length-1)]
}