const frasesHoroscopoAmor = [
    "Hoy, el amor florecerá en tu vida; no dudes en abrir tu corazón.",
    "La conexión que sientes es más profunda de lo que imaginas.",
    "Un nuevo romance podría sorprenderte en los próximos días.",
    "La comunicación será clave para fortalecer tu relación.",
    "No temas expresar tus sentimientos; tu pareja lo valorará.",
    "Un viejo amor podría regresar; considera si es lo que realmente deseas.",
    "Tu energía atraerá a alguien especial; mantente receptivo.",
    "La paciencia será fundamental en tu vida amorosa hoy.",
    "Un pequeño gesto hará que tu ser amado se sienta apreciado.",
    "Confía en tu intuición; te guiará hacia la persona adecuada.",
    "Los malentendidos se resolverán; el amor triunfará.",
    "Un viaje juntos podría reavivar la chispa en tu relación.",
    "La sinceridad en tus palabras fortalecerá el vínculo con tu pareja.",
    "No ignores los signos del universo; te están guiando hacia el amor.",
    "Una sorpresa romántica podría estar en camino; prepárate.",
    "El amor requiere trabajo; hoy es un buen día para invertir en tu relación.",
    "Los solteros encontrarán oportunidades inesperadas para conectar.",
    "La amistad se transformará en algo más; mantén la mente abierta.",
    "No te apresures; el amor verdadero llega a su debido tiempo.",
    "Un encuentro casual podría convertirse en una historia de amor.",
    "Tu actitud positiva atraerá a personas con buenas intenciones.",
    "Escucha a tu corazón; sabe lo que realmente deseas.",
    "Hoy, es un buen día para hacer planes románticos.",
    "La pasión resurgirá; disfruta de los momentos íntimos.",
    "La honestidad será el pilar de tu relación en este momento.",
    "Deja atrás viejas rencillas; el amor merece otra oportunidad.",
    "Un consejo de un amigo te ayudará a aclarar tus sentimientos.",
    "La creatividad en el amor te llevará a nuevas experiencias.",
    "El amor está en el aire; no te lo pierdas.",
    "La risa y el humor serán tus mejores aliados hoy.",
    "No subestimes el poder de un abrazo; puede cambiarlo todo.",
    "Un pequeño detalle puede hacer que tu pareja se sienta especial.",
    "Hoy, tu carisma atraerá a quienes te rodean.",
    "La pasión se renovará; aprovecha este momento.",
    "El amor no tiene edad; no te limites a lo que piensan los demás.",
    "Un mensaje inesperado podría alegrar tu día.",
    "Tu habilidad para escuchar será apreciada por tu pareja.",
    "No temas mostrar tu vulnerabilidad; es un signo de fortaleza.",
    "La conexión emocional será más fuerte que nunca.",
    "Un cambio de ambiente podría revitalizar tu relación.",
    "La confianza es clave; trabaja en construirla con tu pareja.",
    "La amistad y el amor están más cerca de lo que crees.",
    "El amor verdadero vale la pena esperar; no te desesperes.",
    "Una conversación honesta puede cambiar el rumbo de tu relación.",
    "La pasión será intensa; disfruta cada momento.",
    "La empatía te ayudará a comprender mejor a tu ser amado.",
    "No olvides cuidar de ti mismo; el amor florece cuando estamos bien.",
    "Un gesto romántico puede hacer maravillas en tu relación.",
    "La creatividad en el amor te llevará a nuevas alturas.",
    "El amor puede encontrarse en los lugares más inesperados.",
    "Recuerda que el amor también se construye con acciones.",
    "La conexión entre ambos será más fuerte que nunca.",
    "No temas a la intimidad; es un paso importante en la relación.",
    "Un cambio de perspectiva te ayudará a ver el amor con nuevos ojos.",
    "La pasión será el motor de tu relación hoy.",
    "La comunicación abierta evitará malentendidos.",
    "Un momento de calidad juntos será invaluable.",
    "El amor se celebra; planifica algo especial.",
    "La conexión espiritual fortalecerá tu relación.",
    "Un consejo sincero de un amigo puede iluminar tu camino.",
    "No te aferres al pasado; el futuro está lleno de posibilidades.",
    "La confianza será la base de tu relación en este momento.",
    "Un encuentro inesperado podría cambiar tu vida amorosa.",
    "La vulnerabilidad es hermosa; no temas mostrarla.",
    "La química entre ustedes será innegable hoy.",
    "Un pequeño cambio puede traer grandes resultados en el amor.",
    "La risa compartida fortalecerá su vínculo hoy.",
    "La pasión se avivará; disfruta del momento.",
    "Escucha lo que tu corazón tiene que decir.",
    "Un gesto de cariño puede hacer que tu día brille.",
    "La conexión emocional es más importante que nunca.",
    "Un nuevo enfoque en tu relación revitalizará la chispa.",
    "La honestidad y la transparencia son esenciales hoy.",
    "Un viaje juntos podría ser el inicio de algo hermoso.",
    "El amor florece en la adversidad; mantén la fe.",
    "No subestimes el poder de una buena conversación.",
    "La confianza en tu pareja se fortalecerá con el tiempo.",
    "La pasión y la ternura se equilibrarán en tu relación.",
    "Un cambio en tu rutina podría traer novedades románticas.",
    "La empatía será clave para resolver conflictos hoy.",
    "Un pequeño gesto puede hacer que tu pareja se sienta valorada.",
    "La conexión que compartes es única; cuídala.",
    "La sinceridad será el camino hacia un amor más profundo.",
    "Un nuevo comienzo está a la vista; no temas dar el paso.",
    "La risa compartida fortalecerá su relación.",
    "Un momento de silencio puede ser tan valioso como las palabras.",
    "La pasión se reavivará; disfruta de cada instante.",
    "La amistad y el amor son dos caras de la misma moneda.",
    "Un consejo de un ser querido te iluminará el camino.",
    "La vulnerabilidad puede llevar a una conexión más profunda.",
    "Un gesto romántico puede cambiar el rumbo de tu día.",
    "El amor verdadero siempre encuentra la manera de brillar.",
    "La comunicación será el puente hacia la comprensión.",
    "Un pequeño detalle puede hacer que todo valga la pena.",
    "La conexión espiritual entre ustedes se fortalecerá hoy.",
    "Un nuevo amor podría sorprenderte en un lugar inesperado.",
    "La pasión y el compromiso se entrelazan en tu relación.",
    "Las experiencias compartidas crearán recuerdos inolvidables.",
    "La sinceridad es el camino hacia una relación duradera.",
    "El amor es un viaje; disfruta cada paso en el camino."
]

function getFraseHoroscopoAmorRandom(){
    return frasesHoroscopoAmor[getRandomInt(frasesHoroscopoAmor.length-1)]
}