const frasesLocura = [
    "Pies, ¿para qué los quiero si tengo alas para volar?",
    "La locura es como un espejo, te muestra lo que realmente eres.",
    "En mis sueños, siempre soy libre.",
    "La vida sin amor es como un árbol sin flores.",
    "Mis heridas son mi fuerza, son mi voz.",
    "Soy una mujer que se siente como un león en una jaula.",
    "A veces, creo que soy dos: una que ama y otra que teme.",
    "La tristeza es un estado de ánimo, pero la locura es un arte.",
    "Vivo en un mundo donde el dolor y la belleza son uno.",
    "La vida es un juego de locura y pasión.",
    "Soy mi propia musa, mi locura es mi inspiración.",
    "La realidad es solo una ilusión que yo elijo romper.",
    "La locura es un refugio para los que se sienten diferentes.",
    "Mis pensamientos son como mariposas: bellos, pero impredecibles.",
    "Desnudar mi alma es mi forma de ser libre.",
    "El caos en mi mente es el arte en mi lienzo.",
    "La vida me duele, pero también me enseña a amar.",
    "Mis lágrimas son pinceladas de color en mi vida.",
    "El dolor es temporal, pero la locura es eterna.",
    "Cada día es una batalla entre la razón y la locura en mi corazón.",
    "Soy la tormenta y la calma, todo en uno.",
    "Las cicatrices son la historia de mi vida escrita en mi piel.",
    "En mi locura, encuentro la claridad que el mundo ignora.",
    "El arte es mi forma de gritar sin ser escuchada.",
    "Los sueños son el refugio de mis locuras.",
    "La belleza y el dolor son mis eternos compañeros.",
    "A veces, me pierdo en el laberinto de mis pensamientos.",
    "La pasión es un fuego que consume mi locura.",
    "Mis colores son gritos de lo que llevo dentro.",
    "El amor es un acto de locura que vale la pena.",
    "La vida es un lienzo, y yo soy la pintora de mis locuras.",
    "Cada lágrima es un trazo de mi historia.",
    "La locura es una danza en la que todos somos bailarines.",
    "Las sombras de mi mente son mis mejores aliadas.",
    "Soy un rompecabezas de emociones, siempre incompleta.",
    "La libertad es un estado de locura que busco.",
    "Mis pensamientos son ríos caudalosos que fluyen sin control.",
    "La vida es un sueño, y yo soy su más loca soñadora.",
    "En la locura, encuentro la esencia de la vida.",
    "Soy un espejo roto que refleja la belleza del caos.",
    "Estoy en forma... redonda es una forma, ¿no?",
    "Mis ideas son como mi cabello: a veces un poco enredadas.",
    "Soy multitasking: puedo desordenar la casa y comer al mismo tiempo.",
    "La locura es solo un estado de ánimo… y el mío es festivo.",
    "Si la vida te da limones, ¡haz limonada y añádele vodka!",
    "No estoy loca, solo tengo una imaginación muy activa.",
    "Soy como un rompecabezas: a veces falta una pieza… o muchas.",
    "¿Quién necesita un plan? La locura es mi GPS.",
    "Soy la reina de la procrastinación, ¡y tengo un trono de almohadas!",
    "La vida es corta, así que ríe mientras tengas dientes.",
    "Mis plantas son mis mejores amigas… nunca me juzgan.",
    "Soy un desastre, pero un desastre fabuloso.",
    "La razón por la que no hago ejercicio es porque no puedo encontrar mis zapatillas.",
    "Mi espíritu animal es un unicornio… en un día de spa.",
    "Siempre sigo mi corazón… y a veces me lleva a la nevera.",
    "Soy como el Wi-Fi: a veces no puedo conectar.",
    "¿Planificar? No, gracias. Prefiero la aventura de lo inesperado.",
    "Me encanta el silencio… ¡pero solo en mi cabeza!",
    "No tengo problemas, solo situaciones de alto entretenimiento.",
    "El chocolate es mi terapia, y soy una adicta a la sanación.",
    "No necesito un príncipe, solo pizza y una buena serie.",
    "Soy tan especial que incluso mis locuras tienen locuras.",
    "La vida es como un chiste: si no te ríes, es porque no lo entendiste.",
    "Mis ideas son como mis calcetines: a veces están desparejadas.",
    "No estoy hablando sola, solo estoy teniendo una reunión.",
    "Soy la única persona que puede hacer un desastre en una tienda de dulces.",
    "La locura es solo creatividad sin límites.",
    "Si pudiera ser cualquier cosa, sería un sofá… cómodo y siempre ocupado.",
    "Soy un paquete de sorpresas… y a veces, un paquete de papas fritas.",
    "Mi vida es como un reality show… sin las cámaras.",
    "La risa es el mejor remedio, y yo tengo una farmacia.",
    "No soy desorganizada, simplemente tengo un estilo único.",
    "Hoy decidí ser normal… pero eso es muy aburrido.",
    "Mis ideas son como burbujas: brillantes y a veces explotan.",
    "Soy la prueba de que la locura puede ser divertida.",
    "No tengo un plan de vida, solo una lista de cosas que no debo hacer.",
    "Si no puedo reírme de mí misma, entonces, ¿quién lo hará?",
    "La vida es un juego, y yo soy la jugadora más loca.",
    "Amo la lluvia… porque no se ve mi pelo despeinado.",
    "Soy un rompecabezas con muchas piezas perdidas.",
    "Me dicen que soy un poco loca, pero prefiero ser única.",
    "Soy un caos organizado… o un desastre bien intencionado.",
    "Mis sueños son tan grandes que a veces no caben en mi cabeza.",
    "La locura es solo otra forma de ser genial.",
    "Si el café no me despierta, entonces la locura lo hará.",
    "Soy la reina del '¿qué estaba haciendo?'",
    "La vida es como un burrito: a veces se desarma, pero sigue siendo deliciosa.",
    "No tengo una crisis de los 30, tengo una fiesta de los 30.",
    "La locura es mi superpoder… ¡y lo uso a diario!",
    "Soy como un reloj roto: siempre estoy en hora… para el caos."
]

function getFraseLocura(){
    return frasesLocura[getRandomInt(frasesLocura.length-1)]
}