const frasesHoroscopoSalud = [
    "Hoy es un buen día para comenzar una nueva rutina de ejercicios.",
    "Escucha a tu cuerpo; te está pidiendo descanso.",
    "La meditación te ayudará a encontrar equilibrio mental.",
    "Cuida tu alimentación; pequeños cambios traerán grandes beneficios.",
    "Mantente hidratado; el agua es esencial para tu bienestar.",
    "Un paseo al aire libre revitalizará tu energía.",
    "La práctica de yoga te traerá paz y estabilidad.",
    "No ignores los signos de fatiga; tu cuerpo necesita reposo.",
    "Un chequeo médico te dará tranquilidad y seguridad.",
    "Dedica tiempo a actividades que te hagan feliz hoy.",
    "La risa es un excelente remedio; busca momentos de alegría.",
    "La conexión con la naturaleza te renovará el espíritu.",
    "Hoy, presta atención a tu salud mental; es igual de importante.",
    "La música puede ser una gran terapia; escoge tus canciones favoritas.",
    "Practicar la gratitud mejorará tu bienestar emocional.",
    "Un cambio en tu dieta te hará sentir más ligero y saludable.",
    "La respiración consciente te ayudará a reducir el estrés.",
    "No subestimes el poder de un buen sueño; te revitalizará.",
    "Conéctate con amigos; las relaciones positivas son clave para la salud.",
    "Escoge alimentos frescos y nutritivos para fortalecer tu sistema.",
    "La actividad física regular es esencial para tu bienestar.",
    "Un masaje puede aliviar tensiones acumuladas en tu cuerpo.",
    "La naturaleza tiene un poder curativo; disfruta de un día al aire libre.",
    "La meditación diaria te ayudará a encontrar claridad mental.",
    "Establece límites; cuidar de ti mismo es una prioridad.",
    "Un hobby creativo te proporcionará satisfacción y relajación.",
    "La salud emocional es tan importante como la física; no la descuides.",
    "La risa compartida fortalecerá tu sistema inmunológico.",
    "Un baño relajante te ayudará a liberar tensiones.",
    "La postura corporal adecuada es esencial para tu salud.",
    "Escucha a tu intuición; te guiará hacia elecciones saludables.",
    "Un día de descanso te permitirá recargar energías.",
    "La alimentación consciente te ayudará a sentirte más conectado contigo mismo.",
    "La práctica de la gratitud mejorará tu salud mental.",
    "Un entorno limpio y ordenado contribuirá a tu bienestar.",
    "La calidad de tus pensamientos influye en tu salud; mantén una mentalidad positiva.",
    "La simplicidad en tu vida te traerá tranquilidad.",
    "Aprende a decir no; cuidar de ti mismo es fundamental.",
    "La risa es el mejor remedio; busca momentos de alegría.",
    "Dedica tiempo a respirar profundamente; te ayudará a relajarte.",
    "La conexión con tu cuerpo te permitirá identificar necesidades.",
    "Un tiempo a solas te ayudará a recargar energías.",
    "La práctica de ejercicios de respiración puede aliviar el estrés.",
    "La salud es un viaje; aprecia cada paso en el camino.",
    "Mantén un equilibrio entre trabajo y descanso; ambos son necesarios.",
    "La naturaleza te ofrece un refugio; busca momentos al aire libre.",
    "Tu salud mental requiere atención; no la descuides.",
    "La creatividad puede ser una vía de sanación; exprésate.",
    "Un cambio en tu rutina te proporcionará novedades refrescantes.",
    "La autoaceptación es clave para una buena salud emocional.",
    "La alimentación balanceada te dará energía y vitalidad.",
    "Escucha los ritmos de tu cuerpo; te guiarán hacia el bienestar.",
    "Dedica tiempo a la relajación; es esencial para la salud.",
    "Un entorno positivo te ayudará a mantener la motivación.",
    "La meditación te conectará con tu ser interior.",
    "Aprecia los pequeños momentos; son los que nutren el alma.",
    "Un día de desconexión te permitirá recargar energías.",
    "La salud es un regalo; cuídala con amor y atención.",
    "La práctica de la gratitud atraerá más cosas buenas a tu vida.",
    "Un cambio en tu perspectiva puede mejorar tu bienestar.",
    "La actividad física no solo tonifica el cuerpo, también la mente.",
    "La conexión con otros te aportará apoyo emocional.",
    "No subestimes el poder de un buen libro; puede ser terapéutico.",
    "La risa compartida es un bálsamo para el alma.",
    "Un hobby puede ser una excelente vía de escape.",
    "La calidad de tus relaciones influye en tu salud emocional.",
    "Practica la autocompasión; ser amable contigo mismo es esencial.",
    "Un día de spa en casa puede ser revitalizante.",
    "La salud es un equilibrio; busca armonía en todas las áreas de tu vida.",
    "La alimentación consciente te conectará con tu cuerpo.",
    "La conexión con animales puede traer alegría y sanación.",
    "Un paseo por la playa o el campo puede ser muy revitalizante.",
    "La práctica regular de ejercicio te proporcionará claridad mental.",
    "Escucha música relajante para calmar tu mente.",
    "La aromaterapia puede ser una herramienta poderosa para tu bienestar.",
    "Dedica tiempo a lo que realmente amas; es esencial para tu salud.",
    "La conexión con tu espiritualidad puede ofrecerte paz.",
    "Un cambio en tu rutina puede abrir nuevas oportunidades de salud.",
    "La salud es un viaje personal; respeta tu propio ritmo.",
    "Un poco de tiempo al aire libre puede hacer maravillas por ti.",
    "La gratitud por tu cuerpo te ayudará a cuidarlo mejor.",
    "Un espacio ordenado te permitirá pensar con claridad.",
    "La práctica de la atención plena te ayudará a disfrutar el presente.",
    "La risa y el juego son esenciales para mantener la alegría.",
    "Escoge actividades que nutran tu cuerpo y alma.",
    "La salud es un equilibrio entre cuerpo, mente y espíritu.",
    "Un pequeño cambio puede hacer una gran diferencia en tu bienestar.",
    "Tu salud mental es tan importante como tu salud física; no la descuides.",
    "Un momento de reflexión puede ofrecerte claridad.",
    "La conexión con tus emociones es clave para una buena salud.",
    "La naturaleza tiene un poder sanador; busca momentos en ella.",
    "La práctica de la bondad contigo mismo fortalecerá tu salud emocional.",
    "Un entorno armonioso te permitirá prosperar.",
    "La autoaceptación es esencial para vivir en paz.",
    "Busca momentos de quietud; la paz mental es crucial.",
    "La calidad de tus pensamientos influye en tu bienestar físico.",
    "Un cambio en la rutina de ejercicio puede revitalizar tu energía.",
    "La meditación puede ser una herramienta poderosa para el autocuidado.",
    "La vida es un viaje; disfruta cada paso hacia tu bienestar.",
    "La salud es tu mayor tesoro; cuídala con amor y dedicación."
]

function getFraseHoroscopoSaludRandom(){
    return frasesHoroscopoSalud[getRandomInt(frasesHoroscopoSalud.length-1)]
}