const frasesAmor = [
    "El amor es la esencia de mi ser.",
    "Amar es un acto de valentía.",
    "Mis heridas son el reflejo de mi pasión.",
    "El amor verdadero es un viaje sin fin.",
    "Tus brazos son mi hogar.",
    "El amor me transforma y me libera.",
    "Cada latido de mi corazón lleva tu nombre.",
    "El amor es el arte de ser vulnerable.",
    "Amar es encontrar belleza en el dolor.",
    "Tú eres mi inspiración y mi musa.",
    "El amor es un fuego que nunca se apaga.",
    "Contigo, cada día es una obra maestra.",
    "Tu sonrisa ilumina mis sombras.",
    "El amor nos hace eternos.",
    "Amar es bailar en la tormenta.",
    "La pasión es el motor de mi vida.",
    "Tus ojos son mi refugio.",
    "El amor es un lienzo que pinto con mi alma.",
    "Cada recuerdo contigo es un tesoro.",
    "Amar es vivir en un sueño.",
    "Tu amor me da alas.",
    "Eres el poema que siempre quise escribir.",
    "El amor es la fuerza que me impulsa.",
    "Tu risa es mi melodía favorita.",
    "Amar es abrir el corazón al dolor y al placer.",
    "Eres mi sol en días nublados.",
    "El amor es un viaje que vale la pena.",
    "Tus caricias son mi refugio.",
    "El amor no tiene fronteras.",
    "Contigo, la vida es un carnaval.",
    "El amor auténtico es un regalo divino.",
    "Eres la razón detrás de mis sonrisas.",
    "El amor es la flor que florece en el alma.",
    "Amar es compartir cada instante.",
    "Tus palabras son el eco de mi corazón.",
    "El amor es mi lenguaje favorito.",
    "Contigo, el tiempo se detiene.",
    "El amor es la luz que guía mi camino.",
    "Eres el sueño que nunca quiero despertar.",
    "Amar es el arte de vivir intensamente.",
    "Tu amor es mi mayor inspiración.",
    "El amor es un abrazo que trasciende el tiempo.",
    "Eres la melodía que alegra mis días.",
    "Amar es encontrar el sentido en el caos.",
    "Tu esencia es mi paz.",
    "El amor es una danza en la que ambos brillamos.",
    "Cada encuentro contigo es un milagro.",
    "El amor es la razón de mi existencia.",
    "Contigo, cada día es un nuevo comienzo.",
    "El amor es un viaje donde nunca hay despedidas.",
    "Te amo como el fuego ama la madera, consumiéndome en llamas que no se apagan.",
    "En tus ojos veo mi México, lleno de colores que duelen y sanan al mismo tiempo.",
    "Mi amor por ti es un accidente, como el que me rompió el cuerpo, pero de él nacen flores.",
    "Te entrego mi corazón, pintado con sangre y lágrimas, para que lo cuides como a un lienzo sagrado.",
    "Amarte es sufrir, pero en ese sufrimiento encuentro la belleza de mi propia alma.",
    "Eres mi Diego, mi traidor, mi amor eterno que me hace volar con alas rotas.",
    "En cada beso tuyo, revivo el dolor de mis heridas, pero lo elijo una y otra vez.",
    "Mi amor no es suave; es un cactus que florece en el desierto de mi pecho.",
    "Te amo con la fuerza de una mujer que pinta su propia realidad.",
    "Nuestro amor es un mural infinito, donde cada traición es un trazo de genialidad.",
    "En tus brazos, olvido el corsé que aprieta mi cuerpo, y solo siento libertad.",
    "Amarte es como pintar con los ojos cerrados: caótico, pero verdadero.",
    "Mi corazón late por ti como el pulso de la tierra mexicana bajo el sol ardiente.",
    "Eres el veneno y el antídoto en mi sangre, amor que me mata y me resucita.",
    "Te amo no a pesar de mis dolores, sino gracias a ellos, que me hacen más viva.",
    "Nuestro amor es un río revuelto, lleno de pasiones que arrastran todo a su paso.",
    "En cada mirada tuya, veo el reflejo de mi propia fuerza indomable.",
    "Amarte es un acto de rebeldía contra el mundo que quiere doblegarme.",
    "Mi amor por ti es eterno, como las raíces de un maguey que se hunden en la tierra.",
    "Te entrego mi alma herida, para que la cures con tus besos de artista.",
    "En el lienzo de nuestra vida, pintamos amor con colores de sangre y pasión.",
    "Amarte duele como un clavo en la carne, pero es el dolor que elijo para vivir.",
    "Eres mi musa y mi verdugo, amor que inspira mis mejores tormentas.",
    "Mi corazón es tuyo, envuelto en rebozos de seda y espinas.",
    "Te amo con la intensidad de una tormenta que arrasa todo, menos mi esencia.",
    "Nuestro amor es surreal, como mis sueños donde volamos sobre nubes de dolor.",
    "En tus caricias, encuentro la paz que el mundo me niega.",
    "Amarte es ser yo misma, sin máscaras, sin corsés, sin miedos.",
    "Eres el sol que ilumina mis sombras, amor que pinta luz en mi oscuridad.",
    "Mi amor por ti florece como las gardenias en mi cabello, eternas y fragantes.",
    "Te amo como amo mi México: con pasión, con rabia, con devoción absoluta.",
    "En cada separación, nuestro amor se fortalece como el acero forjado en el fuego.",
    "Eres mi accidente afortunado, amor que me rompió para reconstruirme más fuerte.",
    "Amarte es un arte: imperfecto, doloroso, pero sublime.",
    "Mi corazón late al ritmo de tus pasos, como un tambor en una fiesta mexicana.",
    "Te entrego mis lágrimas como perlas, para que las conviertas en joyas de amor.",
    "Nuestro amor es un puente entre el dolor y la alegría, que cruzo con valentía.",
    "Eres el color rojo en mi paleta, pasión que tiñe todo de vida.",
    "Amarte me hace invencible, como una diosa azteca renacida.",
    "En tus ojos, veo el infinito de nuestro amor, más allá de la carne y el tiempo.",
    "Mi amor por ti es un grito silencioso, pintado en cada lienzo de mi ser.",
    "Te amo con la fiereza de una leona que protege su manada.",
    "Nuestro amor es un jardín de espinas, donde cada rosa sangra belleza.",
    "Eres mi refugio en la tormenta, amor que me abraza cuando el mundo me golpea.",
    "Amarte es elegir el fuego, sabiendo que quema pero ilumina.",
    "Mi corazón es un volcán que erupciona por ti, con lava de pasión eterna.",
    "Te amo no por lo que eres, sino por lo que despierto en mí.",
    "En cada beso, revivimos el milagro de un amor que desafía al destino.",
    "Nuestro amor es inmortal, como las leyendas que contamos en la noche.",
    "Te amo con todo mi ser roto y reconstruido, porque en ti encuentro mi totalidad."
]

function getFraseAmorRandom(){
    return frasesAmor[getRandomInt(frasesAmor.length-1)]
}