const frasesHoroscopoDinero = [
    "Hoy, tu esfuerzo será reconocido; no dudes en pedir lo que mereces.",
    "Una oportunidad inesperada podría surgir en tu carrera.",
    "La creatividad será tu mejor aliada en el trabajo hoy.",
    "Mantén la mente abierta a nuevas propuestas laborales.",
    "La colaboración con colegas te llevará a nuevos logros.",
    "Un cambio de enfoque podría mejorar tu situación financiera.",
    "La paciencia será clave para alcanzar tus objetivos profesionales.",
    "Un consejo de un mentor te guiará en la dirección correcta.",
    "La disciplina en tus finanzas traerá estabilidad a tu vida.",
    "Hoy es un buen día para negociar un aumento de sueldo.",
    "Un proyecto en equipo dará frutos inesperados.",
    "La organización será fundamental para tu éxito hoy.",
    "No temas tomar riesgos calculados; podrían llevarte lejos.",
    "Un nuevo socio podría abrir puertas que no imaginabas.",
    "La perseverancia te acercará a tus metas financieras.",
    "La intuición jugará un papel importante en tus decisiones laborales.",
    "Un cambio en tu rutina podría traer grandes resultados.",
    "La confianza en ti mismo te ayudará a destacar en tu trabajo.",
    "Un pequeño ahorro hoy puede hacer una gran diferencia mañana.",
    "La comunicación clara evitará malentendidos en el trabajo.",
    "Un proyecto personal podría convertirse en una fuente de ingresos.",
    "La formación continua será clave para tu crecimiento profesional.",
    "Hoy, tu liderazgo brillará en el entorno laboral.",
    "Un ajuste en tu presupuesto te permitirá gastar con sabiduría.",
    "La adaptabilidad será fundamental en tu entorno laboral.",
    "Un nuevo cliente podría llegar con una propuesta interesante.",
    "La honestidad en tus negociaciones te traerá recompensas.",
    "La atención a los detalles te evitará problemas financieros.",
    "Un cambio de ambiente podría inspirar nuevas ideas en el trabajo.",
    "La confianza en tus habilidades te abrirá puertas.",
    "Un conflicto en el trabajo se resolverá con diplomacia.",
    "La innovación será la clave para destacar entre tus colegas.",
    "Un viejo contacto podría ofrecerte una oportunidad laboral.",
    "La gestión del tiempo será crucial para tu productividad.",
    "Un gesto amable en el trabajo fortalecerá tus relaciones.",
    "La planificación financiera te dará tranquilidad.",
    "Hoy, el trabajo en equipo te llevará a nuevos niveles de éxito.",
    "La perseverancia en tus proyectos dará sus frutos.",
    "Un momento de reflexión te ayudará a tomar decisiones acertadas.",
    "La creatividad en tu trabajo será reconocida por tus superiores.",
    "Un nuevo enfoque en tus finanzas te permitirá ahorrar más.",
    "La confianza en ti mismo atraerá nuevas oportunidades laborales.",
    "Un cambio de perspectiva te ayudará a resolver problemas en el trabajo.",
    "La honestidad en tus tratos financieros te protegerá de sorpresas.",
    "Hoy, tu capacidad de negociación será excepcional.",
    "Un proyecto apasionante se presentará ante ti; no lo dejes escapar.",
    "La constancia en tu trabajo te llevará al éxito.",
    "Un consejo financiero de un amigo te será útil.",
    "La colaboración con otros ampliará tus horizontes laborales.",
    "La claridad en tus objetivos financieros te guiará.",
    "Un nuevo aprendizaje te abrirá puertas en tu carrera.",
    "La intuición te llevará a realizar inversiones acertadas.",
    "Hoy, tu capacidad de liderazgo será puesta a prueba.",
    "Un cambio en tu estrategia laboral podría traer grandes beneficios.",
    "La empatía en el trabajo mejorará el ambiente laboral.",
    "Un pequeño ingreso extra podría llegar de manera inesperada.",
    "La dedicación te llevará a alcanzar tus metas financieras.",
    "Un esfuerzo conjunto con colegas dará frutos en el trabajo.",
    "La claridad en tus finanzas te dará tranquilidad mental.",
    "Hoy es un buen día para actualizar tu currículum.",
    "La adaptabilidad te permitirá enfrentar desafíos laborales con éxito.",
    "Un nuevo proyecto podría ser la oportunidad que esperabas.",
    "La honestidad en el trabajo te ganará el respeto de tus compañeros.",
    "Un cambio en tu rutina podría mejorar tu productividad.",
    "La reflexión sobre tus objetivos te ayudará a reorientar tu carrera.",
    "Tu esfuerzo será recompensado; mantén la fe.",
    "Un nuevo enfoque en tus finanzas te permitirá disfrutar más.",
    "La creatividad será valorada en tu entorno laboral hoy.",
    "Hoy, tu capacidad de resolución de problemas brillará.",
    "Un consejo de un colega te dará una nueva perspectiva.",
    "La comunicación efectiva te ayudará a avanzar en tu carrera.",
    "Un cambio en tus hábitos financieros te traerá estabilidad.",
    "La pasión por tu trabajo te llevará a nuevas alturas.",
    "Un proyecto en solitario te permitirá brillar como nunca.",
    "La constancia en tus esfuerzos te acercará a tus objetivos.",
    "Un cambio de ambiente laboral podría ser revigorizante.",
    "La planificación a largo plazo te permitirá alcanzar tus sueños.",
    "Hoy, tu carisma atraerá la atención de quienes te rodean.",
    "Un pequeño gesto en el trabajo puede marcar la diferencia.",
    "La claridad en tus objetivos financieros te dará dirección.",
    "La formación continua te hará destacar en tu campo.",
    "Un cambio en tu enfoque laboral podría abrir nuevas puertas.",
    "La colaboración será la clave para el éxito en el trabajo hoy.",
    "Un viejo proyecto podría reactivarse y darte nuevas oportunidades.",
    "La visualización de tus metas te ayudará a alcanzarlas.",
    "Un cambio en tu mentalidad atraerá abundancia a tu vida.",
    "La proactividad en el trabajo te llevará lejos.",
    "Un consejo financiero de un experto te beneficiará.",
    "La confianza en tu capacidad de trabajo atraerá nuevas oportunidades.",
    "Hoy, tu capacidad de adaptación brillará en el entorno laboral.",
    "Un pequeño cambio en tus hábitos de gasto puede resultar significativo.",
    "La resolución de conflictos te hará ganar respeto en el trabajo.",
    "Un proyecto en equipo te permitirá aprender de los demás.",
    "La perseverancia en tus finanzas te acercará a la libertad económica.",
    "Hoy es un buen día para hacer networking y ampliar tus contactos.",
    "La honestidad en tus tratos laborales te protegerá.",
    "Un cambio en tu estrategia de ahorro te traerá paz mental.",
    "La pasión por lo que haces te llevará a nuevas oportunidades.",
    "Un momento de reflexión te ayudará a tomar decisiones laborales acertadas.",
    "La gratitud por lo que tienes atraerá más abundancia a tu vida."
]

function getFraseHoroscopoDineroRandom(){
    return frasesHoroscopoDinero[getRandomInt(frasesHoroscopoDinero.length-1)]
}