const frasesConectoras = [
    "No me canso de decir que ",
    "No tengo más pretextos pero", 
    "Es Hora de admitir que ",
    "No hay mas manera de decir que ",
    "Lo siento debo decir que ",
    "No te enojes con migo si ",
    "Debes admitir que ",
    "Mi Madre me dijo que ", 
    "Tus amigos saben que ",
    "Me contaron que ",
    "A veces pienso en voz alta y ",
    "Muy seguido quiero decir que ",
    "Son muchos los motivos para contarte que ",
    "Por que ",
    "No debes mirarme así ",
    "¡Tu piensas lo mismo que yo! ",
    "¡Ni lo intentes! ",
    "Admítelo eres pobre y ",
    "¿por que me miras? ",
    "¿por que no me miras? ", 
    "¿por que me escuchas? ",
    "¿por que no me escuchas? ",
    "No te asombres si te digo que ",
    "Mientras estés con migo ",
    "En este día ",
    "A veces pienso en ti ",
    "¿Que duda te cabe? ",
    "¡Hablemos sin saber! ",
    "Según mis registros encontré que ",
    "Según mis datos veo que ",
    "En mi base de datos encontré que ",
    "No creo que quieras escuchar que ",
    "No creo que quieras saber que ",
    "Te veo poco interesado en saber que ",
    "¡No me quiero meter en problemas! Pero ",
    "¿por si o por no?",
    "Si claro por supuesto ",
    "Me alegro de saber que ",
    "como te dije antes",
    "solo se que no se nada",
    "sabemos que",
    "me alegra saber que",
    "Sabías que ",
    "Es mucho muy importante saber que ",
    "Vos sabés que ",
    "¡Siempre y cuando! ",
    "Más vale tarde que nunca "
]

function getFraseConectoraRandom(){
    return frasesConectoras[getRandomInt(frasesConectoras.length-1)]
}