const frasesAlegria = [
    "La alegría es mi refugio.",
    "Celebro cada color que la vida me ofrece.",
    "Cada rayo de sol es un abrazo de amor.",
    "La felicidad se encuentra en los pequeños detalles.",
    "Sonríe, la vida es un lienzo en blanco.",
    "La risa es la música de mi alma.",
    "Bailar es vivir con alegría.",
    "El arte me hace sentir viva.",
    "El amor es la chispa que enciende mi espíritu.",
    "Cada día es una nueva oportunidad para ser feliz.",
    "Las flores son mi expresión de alegría.",
    "La libertad de ser yo misma es mi mayor felicidad.",
    "Mis sueños son la fuente de mi alegría.",
    "El dolor se transforma en arte y en risa.",
    "La vida es una fiesta llena de colores.",
    "La alegría es rebelde y valiente.",
    "Mi corazón es un jardín de risas.",
    "La belleza está en la autenticidad.",
    "Las lágrimas también pueden ser de alegría.",
    "Cada paso es un baile hacia la felicidad.",
    "La vida es un viaje lleno de sorpresas.",
    "Mis raíces son la fuente de mi alegría.",
    "La amistad es un regalo que enriquece mi vida.",
    "El amor propio es la verdadera felicidad.",
    "La pasión es la chispa de mi alegría.",
    "Cada cicatriz cuenta una historia de fortaleza.",
    "La naturaleza es mi musa y mi alegría.",
    "La risa compartida es un tesoro.",
    "El arte es mi forma de celebrar la vida.",
    "La alegría se encuentra en el presente.",
    "Cada día es un nuevo lienzo para pintar.",
    "La vida es un poema lleno de colores.",
    "Las pequeñas cosas traen grandes alegrías.",
    "El coraje es mi compañera en la alegría.",
    "Mis sueños vuelan alto y libres.",
    "El amor transforma mi dolor en alegría.",
    "Cada amanecer es una promesa de felicidad.",
    "Las palabras pueden bailar al ritmo de la alegría.",
    "La vida es un abrazo eterno.",
    "El arte de vivir es celebrar cada momento.",
    "Las emociones son las pinceladas de mi vida.",
    "La alegría es un acto de resistencia.",
    "Las montañas son mis aliadas en la búsqueda de felicidad.",
    "La autenticidad es la clave de mi alegría.",
    "Las risas son el eco de mi espíritu libre.",
    "La vida es un viaje de exploración y alegría.",
    "Las sombras también pueden danzar con luz.",
    "La alegría se encuentra en la conexión con los demás.",
    "Mis raíces son profundas, pero mis alas son libres.",
    "Cada momento es un regalo, disfrútalo con alegría."
]

function getFraseAlegriaRandom(){
    return frasesAlegria[getRandomInt(frasesAlegria.length-1)]
}