const frasesAmor = [
    "El amor es la esencia de mi ser.",
    "Amar es un acto de valentía.",
    "Mis heridas son el reflejo de mi pasión.",
    "El amor verdadero es un viaje sin fin.",
    "Tus brazos son mi hogar.",
    "El amor me transforma y me libera.",
    "Cada latido de mi corazón lleva tu nombre.",
    "El amor es el arte de ser vulnerable.",
    "Amar es encontrar belleza en el dolor.",
    "Tú eres mi inspiración y mi musa.",
    "El amor es un fuego que nunca se apaga.",
    "Contigo, cada día es una obra maestra.",
    "Tu sonrisa ilumina mis sombras.",
    "El amor nos hace eternos.",
    "Amar es bailar en la tormenta.",
    "La pasión es el motor de mi vida.",
    "Tus ojos son mi refugio.",
    "El amor es un lienzo que pinto con mi alma.",
    "Cada recuerdo contigo es un tesoro.",
    "Amar es vivir en un sueño.",
    "Tu amor me da alas.",
    "Eres el poema que siempre quise escribir.",
    "El amor es la fuerza que me impulsa.",
    "Tu risa es mi melodía favorita.",
    "Amar es abrir el corazón al dolor y al placer.",
    "Eres mi sol en días nublados.",
    "El amor es un viaje que vale la pena.",
    "Tus caricias son mi refugio.",
    "El amor no tiene fronteras.",
    "Contigo, la vida es un carnaval.",
    "El amor auténtico es un regalo divino.",
    "Eres la razón detrás de mis sonrisas.",
    "El amor es la flor que florece en el alma.",
    "Amar es compartir cada instante.",
    "Tus palabras son el eco de mi corazón.",
    "El amor es mi lenguaje favorito.",
    "Contigo, el tiempo se detiene.",
    "El amor es la luz que guía mi camino.",
    "Eres el sueño que nunca quiero despertar.",
    "Amar es el arte de vivir intensamente.",
    "Tu amor es mi mayor inspiración.",
    "El amor es un abrazo que trasciende el tiempo.",
    "Eres la melodía que alegra mis días.",
    "Amar es encontrar el sentido en el caos.",
    "Tu esencia es mi paz.",
    "El amor es una danza en la que ambos brillamos.",
    "Cada encuentro contigo es un milagro.",
    "El amor es la razón de mi existencia.",
    "Contigo, cada día es un nuevo comienzo.",
    "El amor es un viaje donde nunca hay despedidas."
]

function getFraseAmorRandom(){
    return frasesAmor[getRandomInt(frasesAmor.length-1)]
}